ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695AD069C2682C4C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A5BEE23F41}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A5BEE23C74}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A5491EB1E6}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A5491EB129}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A566D4B5DD}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A566D4BAFC}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A56D032C4C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A56D032D82}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A553D8A190}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{699544A663D347F7}" {
     m_Actor "MICH_BARMEN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5E72B6BD7F6}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695AD5E72B6BD0BB}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5E77097BF88}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E77097B831}" {
     m_fBuyPrice 35000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E77097B835}" {
     m_TiersSpawn {
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695AD5E77097B837}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5E640369A4D}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E640369AD2}" {
     m_fProtectionPsyLevel 100
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E640369AD6}" {
     m_TiersSpawn {
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE7807E523A}" {
   m_Prefab "{A22C976003AA5BA3}Prefabs/Characters/HeadGear/Hat_Ushanka_01/Hat_Ushanka_01_folded.et"
   m_ChildrensPrefabs {
    "{323641C91965842E}Prefabs/Characters/HeadGear/Hat_Ushanka_01/Hat_Ushanka_01_unfolded.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E640369AD2}" {
     m_fBuyPrice 1000
     m_fProtectionRadiactiveLevel 5
     m_fProtectionPsyLevel 0
     m_fProtectionThermoLevel 5
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E640369AD6}" {
     m_TiersSpawn {
      "TIER_1"
     }
     m_iDescreaseMin 29
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695AD5E640369AC9}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{699544A678C621E8}" {
     m_Actor "MICH_BARMEN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}