ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695AD5E77097BF88}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E77097B831}" {
     m_fBuyPrice 35000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E77097B835}" {
     m_TiersSpawn {
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695AD5E77097B837}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5E640369A4D}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E640369AD2}" {
     m_fProtectionPsyLevel 100
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E640369AD6}" {
     m_TiersSpawn {
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE7807E523A}" {
   m_Prefab "{A22C976003AA5BA3}Prefabs/Characters/HeadGear/Hat_Ushanka_01/Hat_Ushanka_01_folded.et"
   m_ChildrensPrefabs {
    "{323641C91965842E}Prefabs/Characters/HeadGear/Hat_Ushanka_01/Hat_Ushanka_01_unfolded.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5E640369AD2}" {
     m_fBuyPrice 1000
     m_fProtectionRadiactiveLevel 5
     m_fProtectionPsyLevel 0
     m_fProtectionThermoLevel 5
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695AD5E640369AD6}" {
     m_TiersSpawn {
      "TIER_1"
     }
     m_iDescreaseMin 29
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695AD5E640369AC9}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}