ARMST_CRAFT_DATA_LIST {
 m_CraftList {
  ARMST_CRAFT_DATA_INFO "{6A097E1ED55FF91D}" {
   m_PrefabCraft "{1472B9856B26B931}Prefabs/Items/Food/armst_itm_food_tushonka_1.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1EED3569A1}" {
     m_PrefabCraft1 "{5DDC31EAA3B77A02}Prefabs/Items/Mut_parts/armst_itm_mut_boar.et"
     m_PrefabCraft1_count 3
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1EFE903C64}" {
   m_PrefabCraft "{78268D65D7E2361F}Prefabs/Items/Food/armst_itm_food_tushonka_2.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1EFE903CE4}" {
     m_PrefabCraft1 "{D1AC668756A426B5}Prefabs/Items/Mut_parts/armst_itm_mut_rat.et"
     m_PrefabCraft1_count 5
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1E8AC2AFEE}" {
   m_PrefabCraft "{412D824412DA9D97}Prefabs/Items/Food/armst_itm_food_fish.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1E8AC2AC7F}" {
     m_PrefabCraft1 "{7CF638CD443BFA1A}Prefabs/Items/Mut_parts/armst_itm_mut_erb.et"
     m_PrefabCraft1_count 1
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1E86CFFBE0}" {
   m_PrefabCraft "{0202B1521F180725}Prefabs/Items/Food/armst_itm_food_fish2.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1E86CFF853}" {
     m_PrefabCraft1 "{2DF0083E0461CE94}Prefabs/Items/Mut_parts/armst_itm_mut_spider.et"
     m_PrefabCraft1_count 2
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1EAC462579}" {
   m_PrefabCraft "{F6D97BFA381DC370}Prefabs/Items/Food/armst_itm_food_mre.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1EAC462525}" {
     m_PrefabCraft1 "{FAEC8DA797CAFC05}Prefabs/Items/Mut_parts/armst_itm_mut_nightstalker.et"
     m_PrefabCraft1_count 1
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1EA4BA2920}" {
   m_PrefabCraft "{F6D97BFA381DC370}Prefabs/Items/Food/armst_itm_food_mre.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1EA4BA29A9}" {
     m_PrefabCraft1 "{5DDC31EAA3B77A02}Prefabs/Items/Mut_parts/armst_itm_mut_boar.et"
     m_PrefabCraft1_count 3
     m_PrefabCraft2 "{2DF0083E0461CE94}Prefabs/Items/Mut_parts/armst_itm_mut_spider.et"
     m_PrefabCraft2_count 3
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1EB61F4E01}" {
   m_PrefabCraft "{6993C08FA6BAA2FE}Prefabs/Weapons/Rifles/AR15/Rifle_Pronto_AR15_Base.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1E4C03CEBC}" {
     m_PrefabCraft1 "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
     m_PrefabCraft1_count 1
     m_PrefabCraft2 "{7C781C0013B6BFA6}Prefabs/Items/Tools/armst_itm_weap_part_nato.et"
     m_PrefabCraft2_count 4
    }
   }
  }
  ARMST_CRAFT_DATA_INFO "{6A097E1EB66CE30F}" {
   m_PrefabCraft "{96DFD2E7E63B3386}Prefabs/Weapons/Rifles/AK74/armst_AK74N.et"
   m_aCraftItems {
    ARMST_CRAFT_DATA_PARTS "{6A097E1E568D40BB}" {
     m_PrefabCraft1 "{FA0E25CE35EE945F}Prefabs/Weapons/Rifles/AK74/armst_AKS74UN.et"
     m_PrefabCraft1_count 1
     m_PrefabCraft2 "{7958E7B32068CF1D}Prefabs/Items/Tools/armst_itm_weap_part_rus.et"
     m_PrefabCraft2_count 3
    }
   }
  }
 }
}