ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2EFED904C5F}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EFED904CF1}" {
     m_fProtectionRadiactiveLevel 4
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE000221515}" {
   m_Prefab "{907106BB556066E9}Prefabs/Characters/HeadGear/Balaclava/Balaclava_Three-Hole_Black.et"
   m_ChildrensPrefabs {
    "{F3DF25E70C82E9CA}Prefabs/Characters/HeadGear/Balaclava/Balaclava_Three-Hole_Olive.et"
    "{C500301CF7AE1ACB}Prefabs/Characters/HeadGear/Balaclava/Balaclava_Wool_Black.et"
    "{09843B703114507C}Prefabs/Characters/HeadGear/Balaclava/Balaclava_Wool_Olive.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EFED904CF1}" {
     m_fProtectionRadiactiveLevel 4
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{698CE54E0E6EE21E}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}