ARMST_DIALOGS_CONFIG {
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{6942A16EF800F2D6}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6942A16EF8D8203A}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6942A16E3E0C14CF}" {
   m_sLocationPrices 80000
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}