ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{691E7EA8FA99B388}" {
   m_sTraderCategoryName6 ARMST_TRADER_OTHERS
   m_sTraderCategoryName7 ARMST_TRADER_OTHERS
   m_sTraderCategoryName8 ARMST_TRADER_OTHERS
   m_sTraderCategoryName9 ARMST_TRADER_OTHERS
   m_sTraderCategoryName10 ARMST_TRADER_OTHERS
   m_sTraderCategoryName11 ARMST_TRADER_OTHERS
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{693465B3EEA4476A}" {
   m_RewardMoney 14000
  }
 }
}