ARMST_DIALOGS_CONFIG {
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{6913001BB4C0081D}" {
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6913001BB5B1880C}" {
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6913001A6FFFFE17}" {
   m_fMinimalReputation -100
  }
 }
}