ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{69145A66A093F2AD}" {
   m_sTraderCategoryName3 ARMST_TRADER_EQUIPMENTS
   m_sTraderCategoryName4 ARMST_TRADER_WEAPON
   m_sTraderCategoryName5 ARMST_TRADER_ATTACHMENT
   m_sTraderCategoryName6 ARMST_TRADER_AMMO
   m_sTraderCategoryName7 ARMST_TRADER_MEDICINE
   m_sTraderCategoryName8 ARMST_TRADER_CLOTHES
   m_sTraderCategoryName9 ARMST_TRADER_TOOLS
   m_sTraderCategoryName11 ARMST_TRADER_FURNITURES
  }
 }
}