ARMST_DIALOGS_CONFIG {
 m_sDialog_2_Scripts Armst_dialog_none
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{69145A64BEF29C67}" {
   m_sLocationPrices 50000
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation 25
  }
  ARMST_FAST_TRAVEL_CONFIG "{69145A64BEF29C91}" {
   m_sLocationPrices 50000
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation 25
  }
 }
}