ARMST_DIALOGS_CONFIG {
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{69145A64BEF29C67}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{69145A64BEF29C91}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}