ARMST_DIALOGS_CONFIG {
 m_Actor "UKM_MEDIC"
 m_sName_Text "Dr. Volodymyr"
 m_sFaction_Text "UKM"
 m_sNews_Texts {
  "{56478C4C9CFC0697}Configs/GAME_SETTING/DIALOGS/Dialogs_Stalkers.conf"
 }
 m_sDialog_1_Scripts Armst_dialog_news
 m_sDialog_2_Scripts Armst_dialog_Heal
 healingPrice 1000
 m_TraderList {
  ARMST_TRADER_CONFIG "{6A0700D91D8C2210}" {
   m_sTraderCategoryName2 ARMST_TRADER_MONEY
   m_sTraderCategoryName6 ARMST_TRADER_TOOLS
  }
 }
}