SCR_NameTagConfig {
 m_aVisibilityRuleset SCR_NameTagRulesetFriendlies "{658C21A0E400637E}" {
  m_eTraceForLOSMode NO_TRACE
 }
 m_aZones {
  SCR_NameTagZone "{658C21A0E4006379}" {
   m_aElements {
    SCR_NTName "{5D9887870EE2CBFF}" {
     m_aEntityStates {
      SCR_NTStateText "{5878A68DE0CE9E48}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateText "{5884CE7C05A113EB}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateText "{658C21A0E4006375}" {
       m_eEntityState HIDDEN
      }
     }
    }
    SCR_NTIconBase "{5D988780FD72C0CE}" {
     m_aEntityStates {
      SCR_NTStateIcon "{5D988792CA83F25B}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateIcon "{5D988792C90BE88E}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateIcon "{658C21A0E4006370}" {
       m_eEntityState HIDDEN
      }
     }
    }
    SCR_NTIconBase "{5D9CD06C8E74938D}" {
     m_aEntityStates {
      SCR_NTStateIcon "{5D9C85D6F526F964}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateIcon "{5D9C85D6F42AE443}" {
       m_eEntityState HIDDEN
      }
      SCR_NTStateIcon "{658C21A0E4006372}" {
       m_eEntityState HIDDEN
      }
     }
    }
   }
  }
 }
}