SCR_NameTagConfig {
 m_aZones {
  SCR_NameTagZone "{66CE799C9A762F4C}" {
   m_aElements {
    SCR_NTName "{5D988780E96BF772}" {
     m_aEntityStates {
      SCR_NTStateText "{5884CE7C05A113EB}" {
       m_eEntityState HIDDEN
       m_fShadowSize 0
      }
     }
     m_fTextSizeMax 0
     m_fTextSizeMin 0
    }
   }
  }
 }
}