SCR_NameTagConfig {
 m_aVisibilityRuleset SCR_NameTagRulesetSingle "{690CAE07FA164DDD}" {
  m_eTraceForLOSMode NO_TRACE
 }
 m_aZones {
  SCR_NameTagZone "{690CAE07FA164DDF}" {
   m_aElements {
    SCR_NTName "{5D988780E96BF772}" {
     m_aEntityStates {
      SCR_NTStateText "{5878A68DE0CE9E48}" {
       m_eEntityState HIDDEN
      }
     }
     m_fTextSizeMax 0
     m_fTextSizeMin 0
    }
   }
  }
 }
}