ARMST_QUEST_DATA_LIST {
 m_aQuestList {
  ARMST_QUEST_DATA_INFO "{69B0C276AD6DB8FA}" {
   m_Quest_Actor_Start ""
  }
  ARMST_QUEST_DATA_INFO "{69B0C276DCBEFDE4}" {
   m_Quest_Actor_Start ""
  }
  ARMST_QUEST_DATA_INFO "{69B0C276C52C9CF8}" {
   m_Quest_Actor_Start ""
  }
  ARMST_QUEST_DATA_INFO "{69B0C276CB4FABEA}" {
   m_Quest_Actor_Start ""
  }
 }
}