SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  WCS_ClientAFKSystem "{631875F26570BBDA}" {
   SecondsBeforeKick 180
   SecondsBeforeKickMessage 100
   MinimumPlayersForKick 80
  }
 }
}