ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{6A6C0426D63A9473}" {
   m_Prefab "{836590E7BCCE9D48}Prefabs/Equipments/Pants/gorka/armst_pants_gorka_UKM.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{6A6C0426D63A93B3}" {
     m_fBuyPrice 2000
     m_RequiredFaction FACTION_ARMY
     m_fProtectionToxicLevel 8
     m_fProtectionRadiactiveLevel 9
     m_fProtectionPhysicalsLevel 10
     m_fProtectionThermoLevel 8
     m_fProtectionElectroLevel 4
     m_fReliableModifierLevel 12
     m_PrefabRepairs "{7CEF426ABDE2DCA1}Prefabs/Items/repairs/armst_itm_repair_clothes.et"
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{6A6C0426D4B5EDC6}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}