ARMST_GAME_CONF : "{4B2A714984C38F26}Configs/GAME_SETTING/GAME_Settings_PVP.conf" {
 m_AdminList +{
 }
 m_CreateCharacter 0
 m_StartIntro 0
 m_FriendlyFireEnable 1
 REPUTATION_LOSS_FRIENDLY_KILL 0
 m_SurgeTimerAmbient 500
 m_SurgeDamage 100
 m_EnableToxicRain 0
 m_AlifePdaMessageEnable 0
 m_EnableAutoMessages 0
 m_EnableDeathMessages 0
 m_SendLifeMessages 0
 m_SendFoundDeathMessages 0
 m_AlifeEnable 0
 m_damageValue 3
 m_DamageRadiactiveLevel 20
 m_ModifierValueEat 1
 m_ModifierValueWater 1
 m_ModifierValuePsy 0
 m_ModifierValueToxic 0
 m_ModifierValueRadiation 0
 m_ShowOnMapPos 0
 m_ShowCompass 0
 m_FactionList {
  ARMST_RESPAWN_FACTION_CONF "{69145A4F957967C1}" {
   m_StartingLoot +{
    "{8C5F655C16438A7D}Configs/GAME_SETTING/STARTING/stalker_starting2.conf"
    "{785722C41B9EE209}Configs/GAME_SETTING/STARTING/stalker_starting3.conf"
   }
  }
 }
}