ARMST_GAME_CONF {
 m_AdminList {
  ""
 }
 m_CreateCharacter 0
 m_StartIntro 0
 REPUTATION_LOSS_FRIENDLY_KILL 2
 m_AlifePdaMessageEnable 0
 m_EnableAutoMessages 0
 m_EnableDeathMessages 0
 m_SendLifeMessages 0
 m_SendFoundDeathMessages 0
 m_damageValue 1.5
 m_ModifierValueEat 0.08
 m_ModifierValueWater 0.08
}