ARMST_GAME_CONF : "{4B2A714984C38F26}Configs/GAME_SETTING/GAME_Settings_BASE.conf" {
 m_AdminList +{
  ""
 }
 m_FriendlyFireEnable 1
 REPUTATION_LOSS_FRIENDLY_KILL 2
 m_MaxPlayerForStop 28
 m_ModifierValueEat -0.04
 m_ModifierValueWater -0.04
 m_FactionList {
  ARMST_RESPAWN_FACTION_CONF "{69145A4F957967C1}" {
  }
  ARMST_RESPAWN_FACTION_CONF "{6A842B5F144BB2FA}" {
   m_sName "Army"
   m_FactionPlayer FACTION_ARMY
   m_StartingLoot {
    "{0E603FD7122EA094}Configs/GAME_SETTING/STARTING/army_starting.conf"
   }
  }
  ARMST_RESPAWN_FACTION_CONF "{6A842B5F2BFB08B4}" {
   m_sName "Monolith"
   m_FactionPlayer FACTION_MUTANTS
   m_StartingLoot {
    "{49911C5D7ADEBC90}Configs/GAME_SETTING/mutant_starting.conf"
   }
  }
 }
}