ARMST_GAME_CONF {
 m_AdminList {
  ""
 }
 m_CreateCharacter 0
 m_StartIntro 0
 REPUTATION_LOSS_FRIENDLY_KILL 2
 m_AlifePdaMessageEnable 0
 m_EnableAutoMessages 0
 m_EnableDeathMessages 0
 m_SendLifeMessages 0
 m_SendFoundDeathMessages 0
 m_damageValue 1.5
 m_ModifierValueEat 0.08
 m_ModifierValueWater 0.08
 m_FactionList {
  ARMST_RESPAWN_FACTION_CONF "{69145A4F957967C1}" {
   m_StartingLoot +{
    "{8C5F655C16438A7D}Configs/GAME_SETTING/STARTING/stalker_starting2.conf"
    "{785722C41B9EE209}Configs/GAME_SETTING/STARTING/stalker_starting3.conf"
   }
  }
 }
}