ARMST_GAME_CONF : "{4B2A714984C38F26}Configs/GAME_SETTING/GAME_Settings_PVP.conf" {
 m_CreateCharacter 0
 m_StartIntro 0
 m_FriendlyFireEnable 1
 REPUTATION_LOSS_FRIENDLY_KILL 2
 m_AlifePdaMessageEnable 0
 m_EnableAutoMessages 0
 m_EnableDeathMessages 0
 m_SendLifeMessages 0
 m_SendFoundDeathMessages 0
 m_AlifeEnable 0
 m_damageValue 3
 m_DamageRadiactiveLevel 20
 m_ModifierValueEat 0.1
 m_ModifierValueWater 0.1
 m_ModifierValueRadiation 0.1
 m_ShowOnMapPos 0
 m_ShowCompass 0
}