ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69B7479415341F3B}" {
   m_PrefabTrader "{9DD2F0D7FED095BC}Prefabs/New_Equipment/Suits/SpecA/armst_suit_specA_mono.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74794151F198C}" {
   m_PrefabTrader "{D98C9A1D5171A5B9}Prefabs/Characters/HeadGear/Helmet_PASGT_01/Helmet_PASGT_01_MONO_cover.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479415068321}" {
   m_PrefabTrader "{C1AFDCB96FE32C74}Prefabs/Armbands/MonolithPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B747941561EA58}" {
   m_PrefabTrader "{456CC7FB44516C48}Prefabs/Armor/MonoVest.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B747941548AA7A}" {
   m_PrefabTrader "{BFDFE9BE16CA447C}Prefabs/New_Equipment/Gasmasks/MV35MONO.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479414B0FF65}" {
   m_PrefabTrader "{D62181862478033C}Prefabs/Characters/Handwear/Gloves_Leather_01/STALKER_eXplorer_CombatGloves_black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74794149B9D59}" {
   m_PrefabTrader "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479414825470}" {
   m_PrefabTrader "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479414E8372F}" {
   m_PrefabTrader "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E3B8C819}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 4
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E3A3761F}" {
   m_PrefabTrader "{CB67A30D05AA4F29}Prefabs/Items/Medicine/armst_itm_medkit_ai2.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E38B6E50}" {
   m_PrefabTrader "{E787ABC7B9D4A084}Prefabs/Items/Medicine/armst_itm_stim_derad.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E3F2270A}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E3DC1212}" {
   m_PrefabTrader "{F6D97BFA381DC370}Prefabs/Items/Food/armst_itm_food_mre.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793E33931EE}" {
   m_PrefabTrader "{77EAE5E07DC4678A}Prefabs/Weapons/Grenades/Smoke_RDG2.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69B747938015329E}" {
   m_PrefabTrader "{FA5C25BF66A53DCF}Prefabs/Weapons/Rifles/AK74/armst_AK74.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793807DA3FD}" {
   m_PrefabTrader "{E5912E45754CD421}Prefabs/Weapons/Magazines/5x45/Magazine_545x39_AK_30rnd_Tracer.et"
   m_iCounts 6
  }
  ARMST_PLAYER_START_CONF_DATA "{69B747938064538C}" {
   m_PrefabTrader "{9A5F80D1F073E8B9}Prefabs/Equipments/patches/armst_pda_equipment.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479380478CC6}" {
   m_PrefabTrader "{65EF51BF87A5CCA3}Prefabs/Items/devices/armst_itm_olimp.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479387ACF0DA}" {
   m_PrefabTrader "{2716BC36E75EBE4E}Prefabs/Items/devices/armst_itm_radon.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69B74793B17A1D67}" {
   m_PrefabTrader "{1D1CF01775CD47F4}Prefabs/Backpacks/Buttpack.et"
  }
 }
}