ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2FBED05791E}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{68F151CD7752D8DB}" {
     m_fPropertiesToxicLevelMax -3.3
     m_fPropertiesRadiactiveLevelMax -1.5
     m_fPropertiesPsyLevelMin -2.4
     m_fPropertiesPsyLevelMax -8.3
     m_fPropertiesHealthLevelMax 12.9
     m_fPropertiesStaminaLevelMax 2.6
     m_fPropertiesBloodLevelMax -2.3
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableSell 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableSell 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{693465A16395AF0B}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{693465A16395AFB1}" {
     m_fPropertiesRadiactiveLevelMin -0.9
     m_fPropertiesRadiactiveLevelMax 1.3
     m_fPropertiesStaminaLevelMin -1.7
     m_fPropertiesStaminaLevelMax 1.8
    }
   }
  }
  ARMST_DATABASE_ITEM "{693465A0934AC536}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{693465A0934AC582}" {
     m_fPropertiesRadiactiveLevelMin -1.8
     m_fPropertiesRadiactiveLevelMax 2.4
     m_fPropertiesEatLevelMin -1.8
     m_fPropertiesEatLevelMax 2.4
    }
   }
  }
  ARMST_DATABASE_ITEM "{693465A09670435A}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{693465A0967043BB}" {
     m_fPropertiesRadiactiveLevelMin -2.3
     m_fPropertiesRadiactiveLevelMax 2.2
     m_fPropertiesHealthLevelMin -8.8
     m_fPropertiesHealthLevelMax 6.5
     m_fPropertiesStaminaLevelMin 1.3
     m_fPropertiesStaminaLevelMax -1
     m_fPropertiesWaterLevelMin -2.1
     m_fPropertiesEatLevelMin 0.9
     m_fPropertiesEatLevelMax 1.9
     m_fPropertiesBloodLevelMin 1.2
     m_fPropertiesBloodLevelMax -2.1
     m_fPropertiesPhysicalsLevelMin -1.3
     m_fPropertiesPhysicalsLevelMax 1.4
    }
   }
  }
  ARMST_DATABASE_ITEM "{693465A0983388D2}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{693465A09833893F}" {
     m_fPropertiesToxicLevelMin 1.8
     m_fPropertiesToxicLevelMax -1.4
     m_fPropertiesRadiactiveLevelMin 1.7
     m_fPropertiesRadiactiveLevelMax 2.5
     m_fPropertiesPsyLevelMin 0.6
     m_fPropertiesPsyLevelMax -1.9
     m_fPropertiesHealthLevelMin -11.1
     m_fPropertiesHealthLevelMax -11.4
     m_fPropertiesStaminaLevelMin 1.5
     m_fPropertiesStaminaLevelMax 1.1
     m_fPropertiesWaterLevelMin 1
     m_fPropertiesWaterLevelMax -1.5
     m_fPropertiesEatLevelMin 1.1
     m_fPropertiesEatLevelMax -1.6
     m_fPropertiesBloodLevelMin 0.9
     m_fPropertiesBloodLevelMax -0.9
     m_fPropertiesPhysicalsLevelMin -1.5
     m_fPropertiesPhysicalsLevelMax -2.4
     m_fPropertiesThermoLevelMin 1
     m_fPropertiesThermoLevelMax 1.4
     m_fPropertiesElectroLevelMin 2.1
     m_fPropertiesElectroLevelMax 1.6
    }
   }
  }
  ARMST_DATABASE_ITEM "{693465A0824B02C0}" {
   m_ItemArt {
    ARMST_DATABASE_ITEM_ART_PROPERTIES "{693465A0824B0320}" {
     m_fPropertiesStaminaLevelMax 3.6
     m_fPropertiesWaterLevelMin -1.8
     m_fPropertiesWaterLevelMax 3.2
     m_fPropertiesEatLevelMin -1.6
     m_fPropertiesPhysicalsLevelMin -3.8
     m_fPropertiesThermoLevelMin 4.7
    }
   }
  }
 }
}