ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2F8DECBDA57}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917673392517A}" {
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2F8C27EE351}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2F8C27EE2BF}" {
     m_fBuyPrice 8000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591767508ECFCD}" {
     m_Category {
      "ELECTRONICS"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2F8C63ED0F4}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2F8C63ED042}" {
     m_fBuyPrice 15000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176746E2D74B}" {
     m_TiersSpawn {
      "TIER_3"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{6972685D2BFD88C7}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{6972685D2BFD897B}" {
     m_fBuyPrice 35000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6972685D2BFD897F}" {
     m_TiersSpawn {
      "TIER_3"
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{6972685D2D6D3D96}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6972685D2D6D3E16}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2F8CAB0A5A1}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2F8CF8F6DB9}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2F8CF8F6D0A}" {
     m_fBuyPrice 30000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917676E2EC571}" {
     m_TiersSpawn {
      "TIER_3"
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2F8F6D49730}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2F8F6D49680}" {
     m_fBuyPrice 40000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF7416000E}" {
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5EA8763248F}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF034408C12}" {
     m_fBuyPrice 15000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
   }
  }
 }
}