ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF9E5462A97}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766DBBC445A}" {
     m_iDescreaseMin 10
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF9EA9D123D}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766CB410A97}" {
     m_iDescreaseMin 19
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF9ECCDECF7}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766F4D7142C}" {
     m_iDescreaseMin 27
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF9EF4F866B}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766FB940E90}" {
     m_iDescreaseMin 37
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF910B4FB50}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766E45FB4C6}" {
     m_iProbability 0.86
     m_iDescreaseMin 9
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF912B0D116}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176611E2478E}" {
     m_iDescreaseMin 15
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF9161BDDAC}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176617B0DCF9}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
     m_iDescreaseMin 9
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF918F5203E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917661CB84A28}" {
     m_iDescreaseMin 14
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF91A218665}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176631A66AE1}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
     m_iDescreaseMin 17
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF91C8CB28A}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917663D9C219B}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
     m_iDescreaseMin 11
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF900A3417A}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176624B486BB}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68D6D22670C6}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591766866EDC8E}" {
     m_iDescreaseMin 17
    }
   }
  }
 }
}