ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF9161BDDAC}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176617B0DCF9}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF91A218665}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176631A66AE1}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF91C8CB28A}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917663D9C219B}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF900A3417A}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176624B486BB}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_2"
     }
    }
   }
  }
 }
}