ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEFA3AEE3848}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFA3AEE383C}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEDEFBFF8ADE74}" {
     m_ArmstChangeRadiactive -20
     m_ArmstChangeEat -15
    }
   }
  }
 }
}