ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEFA3AEE3848}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFA3AEE383C}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEDEFBFF8ADE74}" {
     m_ArmstChangeRadiactive -20
     m_ArmstChangeEat -15
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6958D296BD547366}" {
     m_iDescreaseMin 13
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F3774DD700}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68E8EB8EF1DE}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68E8EB8EF265}" {
     m_iDescreaseMin 11
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68E8ED5C7536}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68E9BCF2C252}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68E8ED8C8086}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA2268F0C7}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F3774DD700}" {
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68E81DF5F84C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F3774DD700}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68E81CEA9D6F}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA24D5439D}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA279F7EBD}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6958D2856E44B5BD}" {
     m_iDescreaseMin 13
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA2D7970D6}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA53A3CBD3}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA5C14909C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{6958BC2ECF73D033}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFA56FCC571}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68F3774DD700}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68F377CDB65E}" {
     m_EnableBuy 0
    }
   }
  }
 }
}