ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EE97D6B33F798A}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EE97D6B33F79DE}" {
     m_fBuyPrice 1000
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EE97D6BFCA1E69}" {
     m_ArmstChangeWater -30
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5B2AE871}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5B2AF7CD}" {
     m_ArmstChangeToxic 4
     m_ArmstChangeRadiactive -10
     m_ArmstChangeWater -15
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5B8AD54F}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5B8AD4B0}" {
     m_ArmstChangeToxic 4
     m_ArmstChangeRadiactive -10
     m_ArmstChangeWater -10
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5CDA7A20}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2FC5CDA7980}" {
     m_fBuyPrice 2500
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5CDA7986}" {
     m_ArmstChangeHP -35
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765821936BE}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5D521BA5}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2FC5D521B07}" {
     m_fBuyPrice 7000
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5D521B0A}" {
     m_ArmstChangeHP -55
     m_ArmstChangeRadiactive -20
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765862E7C5E}" {
     m_TiersSpawn {
      "TIER_3"
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5E5BACD8}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2FC5E5BAC36}" {
     m_fBuyPrice 2500
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5E5BAC35}" {
     m_ArmstChangeHP 10
     m_ArmstChangeToxic 10
     m_ArmstChangeWater -35
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917658C35FDF7}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC5EB9A97E}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2FC5EB9A8D8}" {
     m_fBuyPrice 2000
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC5EB9A8DF}" {
     m_ArmstChangeRadiactive -10
     m_ArmstChangeWater -10
     m_ArmstChangeEat -20
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765B0D9FF91}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC42A1DF40}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2FC42A1DEAA}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC42A1DEAE}" {
     m_ArmstChangeHP 10
     m_ArmstChangeToxic -15
     m_ArmstChangeRadiactive 20
     m_ArmstChangeWater -17
     m_ArmstChangeEat -15
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765BC3EB550}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC42578D82}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC42578DF2}" {
     m_ArmstChangeHP -20
     m_ArmstChangeWater -30
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC431E95A8}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC431E9509}" {
     m_ArmstChangeHP 35
     m_ArmstChangeRadiactive -22
     m_ArmstChangePsy 41
     m_ArmstChangeWater -22
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC601E6DBF}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC601E6D26}" {
     m_ArmstChangeHP 20
     m_ArmstChangeToxic 27
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC7ECF0AAD}" {
   m_ItemConsumable {
    ARMST_DATABASE_ITEM_CONSUMABLE "{68EEB2FC7ECF0A13}" {
     m_ArmstChangeHP -45
     m_ArmstChangeToxic -35
     m_ArmstChangeRadiactive 28
     m_ArmstChangePsy -68
     m_ArmstChangeWater 48
     m_ArmstChangeEat 59
    }
   }
  }
 }
}