ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEE056DF7F1F}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68E4FB0279F9}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEE055CA57BC}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68E448B52905}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFF4FD14307}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68E44BE42712}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFF4FD14301}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176509D5A0BF}" {
     m_TiersSpawn {
      "TIER_3"
     }
    }
   }
  }
 }
}