ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF09A281244}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF09A28124B}" {
     m_fBuyPrice 10000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF09A28124A}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF09A281249}" {
     m_fBuyPrice 13000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF088687961}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF088687936}" {
     m_fBuyPrice 500
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF0893D2F41}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF0893D2F18}" {
     m_fBuyPrice 25000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF08BE0EC4E}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF08BE0ECE2}" {
     m_fBuyPrice 1500
    }
   }
  }
 }
}