ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEFCB2C0F591}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765206D5AC8}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFD55BAF37D}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765281787AE}" {
     m_iProbability 1.29
     m_iDescreaseMin 5
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFD73FF4452}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591765542B024A}" {
     m_iProbability 0.75
     m_iDescreaseMin 6
    }
   }
  }
 }
}