ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695B02B2909C9B73}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B2909C9BBA}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 4.21
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B01372E9EF}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B01372F660}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 5.98
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B586FA3815}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B586FA38F9}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 4.54
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B58D1E2E58}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B58D1E2E35}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 8.64
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B5B65D0FDD}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B5B65D0FBB}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 5.87
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B5BC3820C1}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B5BC3820A2}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 6.53
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B5EEC26346}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B5EEC263CA}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 7.42
    }
   }
  }
  ARMST_DATABASE_ITEM "{695B02B517B87F0E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695B02B517B87FE0}" {
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 9.52
    }
   }
  }
 }
}