ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEFC8846290B}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC88462900}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591764EB38566D}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC88462905}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC88462904}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176417BEB54B}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC88462EFB}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8849CE9E}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917641C3EBA4F}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8849CE9F}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8849CE9C}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917641F0A2AA2}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68EF7B6EDE2F}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFCAA9C011A}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFCAA9C0143}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917640375B819}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF0A1C6C99}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68EF4A65645E}" {
     m_EnableBuy 0
    }
   }
  }
 }
}