ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{69A7440ED044A47C}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69A7440ED044A470}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EF376AD26CA}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69A86EF376AD2746}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE4EEAA989D}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE4EEAA991D}" {
     m_fBuyPrice 10000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE4EDD44B8B}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE4EDD47413}" {
     m_fBuyPrice 20000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE41BE87EDF}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE41BE87F5D}" {
     m_fBuyPrice 26000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE41F3B79C2}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE41F3B7A49}" {
     m_fBuyPrice 11000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE4EFF1DEE0}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE4EFF1DF6B}" {
     m_fBuyPrice 16000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE401439E39}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE401439E87}" {
     m_fBuyPrice 27000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE4038459D5}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE403845A23}" {
     m_fBuyPrice 23000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE4A49DEF65}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE4A49DE80C}" {
     m_fBuyPrice 14000
    }
   }
  }
 }
}