ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695CC1A78F442D62}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A78F4432AD}" {
     m_Actor "MICH_BARMEN"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60238980D6201}" {
     m_Actor "DUTY_VENDOR"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389861A54F}" {
     m_Actor "FREEDOM_VENDOR"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6023898409FA1}" {
     m_Actor "BANDIT_VENDOR"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389FAEA7BF}" {
     m_Actor "UKM_VENDOR"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389F94B9A0}" {
     m_Actor "MONOLITH_VENDOR"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02442}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
 }
}