ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695CC1A78F442D62}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A78F4432AD}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02442}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
 }
}