ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695CC1A78A1B1C6C}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695CC1A78A1B1D61}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A78F442D62}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695CC1A78F4432AD}" {
     m_Actor "MICH_BARMEN"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60238980D6201}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389861A54F}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6023898409FA1}" {
     m_Actor "BANDIT_VENDOR"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389FAEA7BF}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602389F94B9A0}" {
     m_Actor "MONOLITH_VENDOR"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02442}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68EF599747F3}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB0245C}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB0245D}" {
     m_fBuyPrice 5000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917643CD9DAE1}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB0245E}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB02A2D}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02A2B}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176427E45B7E}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02A29}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB02A28}" {
     m_fBuyPrice 2000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB02A27}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB02A1E}" {
     m_fBuyPrice 800
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB1B044}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB1B047}" {
     m_fBuyPrice 1000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB1B046}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB1B041}" {
     m_fBuyPrice 1800
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB1B040}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB1B043}" {
     m_fBuyPrice 1000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC8AB1B042}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC8AB1B04D}" {
     m_fBuyPrice 1800
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFCCDC5CB2E}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFCCDC5CB54}" {
     m_fBuyPrice 1000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFCCD57A8F7}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFCCD57A819}" {
     m_fBuyPrice 1500
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFCCB8E7DD6}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695917639FE26954}" {
     m_TiersSpawn {
      "TIER_1"
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC39B5CE49}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591763B729F5A2}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_1"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC3967AAB2}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEFC3967AA1F}" {
     m_fBuyPrice 1500
    }
   }
  }
  ARMST_DATABASE_ITEM "{69A86EE560856287}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69A86EE56085633A}" {
     m_fBuyPrice 1500
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEFC2F62BCE2}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591763D3A70EEC}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_1"
     }
    }
   }
  }
 }
}