ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2FB361520AF}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591767BCF8F073}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.84
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A209F067}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A20993FC}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.23
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6380DD389}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6380DD060}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.23
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A63DB2209E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A63DB221E1}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.11
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A58DB6A4}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A58DB612}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 2.33
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6ABC6315B}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6ABC636A3}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 0.86
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A83B1CFC}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A83B1C49}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.6
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6AEE2BF77}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6AEE2BCC7}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 2.33
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6AC8BA633}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6AC8BA782}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 2.09
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B2C2321E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B2C2336E}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 2.33
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B7AA1652}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B7AA17B0}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.72
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B5E28175}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B5E286AE}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.47
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6BAF9BA50}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6BAF9BBAB}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 1.84
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A7E68D6CCD}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{6959176570B4AD55}" {
     m_iProbability 1.6
    }
   }
  }
 }
}