ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2FB361520AF}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{69591767BCF8F073}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 6.02
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A209F067}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A20993FC}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 4.55
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6380DD389}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6380DD060}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 4.79
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A63DB2209E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A63DB221E1}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 3.32
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A58DB6A4}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A58DB612}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 4.79
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6ABC6315B}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6ABC636A3}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 4.67
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6A83B1CFC}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6A83B1C49}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 5.41
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6AEE2BF77}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6AEE2BCC7}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6AC8BA633}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6AC8BA782}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 5.9
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B2C2321E}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B2C2336E}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 5.77
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B7AA1652}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B7AA17B0}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 3.93
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6B5E28175}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6B5E286AE}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 3.56
    }
   }
  }
  ARMST_DATABASE_ITEM "{695CC1A6BAF9BA50}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695CC1A6BAF9BBAB}" {
     m_TiersSpawn {
      ""
      "TIER_2"
     }
     m_iProbability 4.91
    }
   }
  }
 }
}