ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2FCC67ED39C}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68C79B91B834}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FCCF3AFED7}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68C79B91B834}" {
     m_TiersSpawn {
      "TIER_2"
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{69392152043BB6DB}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69392152043BB755}" {
     m_fBuyPrice 20000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FCD4179745}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68C79B91B834}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FCC46C7423}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68C79B91B834}" {
     m_TiersSpawn {
      "TIER_2"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE20403D3DA}" {
   m_Prefab "{14ACB395C42FDCD9}Prefabs/Characters/Vests/Vest_Lifchik/Vest_LBV.et"
   m_ChildrensPrefabs {
    "{BBA306E75A847042}Prefabs/Characters/Vests/Vest_Lifchik/Vest_LBV_black.et"
    "{B3D41C94BBEABCB0}Prefabs/Characters/Vests/Vest_Lifchik/Vest_LBV_tan.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{698CBDE20403D051}" {
     m_fBuyPrice 15000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{698CBDE20403D057}" {
     m_Category {
      "EQUIPMENTS"
     }
     m_TiersSpawn {
      "TIER_2"
     }
     m_iProbability 0.6
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{698CBDE20403D04A}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDE20403D04B}" {
     m_Actor "MICH_BARMEN"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
     m_EnableBuy 1
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDE20403D049}" {
     m_Actor "STORM_TRADER"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDE204037B8A}" {
     m_Actor "TUFAN_BARMAN"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDE204037B8C}" {
     m_Actor "URAL_BARMAN"
     m_sTraderCategory ARMST_TRADER_EQUIPMENTS
     m_EnableBuy 0
     m_EnableSell 0
    }
   }
  }
 }
}