WeatherStateMachine {
 States {
  SCR_WeatherState "{660756C16297995A}" {
   Transitions {
    WeatherTransition "{660756C0F69A3D56}" {
     TransitionProbability 0.1
    }
   }
   StateDurationHoursMin 1.067
   StateDurationHoursMax 2.9
  }
 }
}