WeatherStateMachine {
 States {
  SCR_WeatherState "{660756C162979959}" {
   WeatherVariant0 WeatherVariant "{56248BCDA03159B3}" {
    FogPattern WeatherFogPattern "{627CACCC45D343CD}" {
     FogMinAmount 0.2
     FogMaxAmount 0.4
     FogMinHeight 0.2
    }
   }
  }
  SCR_WeatherState "{6A13085888F574A7}" {
   UiLocalizedName "#AR-Weather_Clear"
   UiIcon "{E72405E0209CB3CC}UI/Textures/Editor/Attributes/Weather/Attribute_Weather_Overcast.edds"
   StateName "Clear"
   Transitions {
    WeatherTransition "{6A13085888F546D2}" {
     DestName "Cloudy"
     TransitionProbability 1
     TransitionDurationHoursMin 2
     TransitionDurationHoursMax 4
    }
   }
   StateDurationHoursMin 6
   StateDurationHoursMax 10
   WeatherVariant0 WeatherVariant "{56248BCDA03159B3}" : "{C5EB94785CC16DF3}Terrains/Common/WeatherPresets/StateMachine/Variants/Variant_Overcast_Stratus_armst.conf" {
    VariantName "Cirrus"
    WindPattern WeatherWindPattern "{627CACCC45D343D4}" {
     WindSpeedMin 1
     WindSpeedMax 5
    }
    FogPattern WeatherFogPattern "{627CACCC45D343CD}" {
     FogMaxAmount 0
     FogMaxHeight 0
    }
    WeatherItems WeatherItems "{88F9729E29EEA767}Terrains/Common/WeatherPresets/StateMachine/Items/Variant_Overcast_Stratus_items_armst.conf" {
     SunLightingParams {
      0
      0
      0
      10
      1
      0
      1
      0
      10
      0.937
      0
      2
      0
      10
      0.88
      1
      0
      0
      0
      10
      6
      0
      0
      90
      1
      2
      0
      0
      90
      1
      2
      1
      0
      90
      1
      2
      2
      0
      90
      1
      3
      0
      0
      90
      1
      7
      0
      0
      0
      1.5
      8
      0
      0
      0
      1.5
      9
      0
      0
      90
      1
      9
      1
      0
      90
      1
      9
      2
      0
      90
      1
      10
      0
      0
      90
      1
      10
      1
      0
      90
      1
      10
      2
      0
      90
      1
      4
      0
      0
      90
      0.16
      5
      0
      0
      -88
      0.12
      5
      0
      1
      -20
      0.12
      5
      0
      2
      50
      0.36
      5
      0
      3
      90
      0.4
      45
      0
      0
      -88
      0.16
      45
      0
      1
      -18
      0.16
      45
      0
      2
      60
      0.6
      45
      0
      3
      90
      0.64
      77
      0
      0
      0
      0.2
     }
    }
   }
   StartVariant "Cirrus"
  }
 }
}