SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{687341E4EC2DB1DB}" {
   m_sIdentifier "Clothing"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{687341E4EC2DB1D0}" {
     m_sEntityPrefab "{505D37D63871095C}Prefabs/Items/Equipment/Radios/Radio_SHARD.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{687341E4EC2DB1D3}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{687341E4EC2DB1D5}" {
     m_sEntityPrefab "{95EA40F4AF3ECF5A}Prefabs/Armbands/StalkerGroups/ShardPatch.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{687341E4EC2DB1D4}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{687341E4EC2DB1D7}" {
     m_sEntityPrefab "{1D832E6878BD01E1}Prefabs/New_Equipment/Jackets/gorka/armst_jacket_gorka_camo_shard.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{687341E4EC2DB1D6}" {
       m_eItemType TORSO
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{687341E4EC2DB1A9}" {
     m_sEntityPrefab "{CB372EB39922F8F1}Prefabs/New_Equipment/Pants/gorka/armst_pants_gorka_shard.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{687341E4EC2C7D12}" {
       m_eItemType LEGS
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{687341E4EC2C7D13}" {
     m_sEntityPrefab "{C69291D06C7842DD}Prefabs/Characters/HeadGear/Hood/Hood_Shard.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{687341E4EC2C7D10}" {
       m_eItemType HEADWEAR
      }
     }
    }
   }
  }
 }
}