SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66FB0B388FAF0B46}" {
   m_sIdentifier "Clothing"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66FB0B39DB544136}" {
     m_sEntityPrefab "{BB81D490B52F0016}Prefabs/Items/Equipment/Radios/Radio_SBU.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66FB0B39DB544196}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66FB0B3D28A58F25}" {
     m_sEntityPrefab "{B31E1C14FCC87D7C}Prefabs/Armbands/SBUPatch.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66FB0B3D28A58E8E}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66FB0B388FAF0B4B}" {
     m_sEntityPrefab "{A5FB4C60B1377C01}Prefabs/Armor/MilitaryBeril.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66FB0B388FAF0B4A}" {
       m_eItemType TORSO
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{689B7BFE033E1F8A}" {
     m_sEntityPrefab "{52D90A0F699DBFAC}Prefabs/Armor/Army6b45.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689B7BFE033E1F6A}" {
       m_eItemType TORSO
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66FB0B384C622EDC}" {
     m_sEntityPrefab "{5B49F3A8511A3C47}Prefabs/Helmet/MilitaryBerillHelmet.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66FB0B384C622D3E}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{689B7BEB020367A5}" {
     m_sEntityPrefab "{9569C93EC28CC980}Prefabs/Helmet/MilitaryHelmet.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689B7BEB0203672B}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{689B7BFE12C17E0B}" {
     m_sEntityPrefab "{B16BDA1F98DF16F7}Prefabs/New_Equipment/Jackets/gorka/armst_jacket_army_camo.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689B7BFE12C17D78}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{689B7BFE0B90014B}" {
     m_sEntityPrefab "{FD1C70E08FD097F7}Prefabs/New_Equipment/Pants/gorka/armst_pants_gorka_army.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689B7BFE0B90012C}" {
       m_eItemType HEADWEAR
      }
     }
    }
   }
  }
 }
}