ARMST_ALIFE_MAIN_CONFIG {
 m_LocationsConf {
  ARMST_ALIFE_LOCATION_CONFIG "{690E617E3A77B1DA}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 497
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C66C9F0D7}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 558
  }
  ARMST_ALIFE_LOCATION_CONFIG "{69245ACF62C9F73E}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 764
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C690578F2}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 606
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C771D9434}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 586
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C03D43EB5}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 673
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C04F6C9EC}" {
   m_MinGroupsLocation 2
   m_CheckTimerLocation 808
  }
  ARMST_ALIFE_LOCATION_CONFIG "{693A786FAE6CBBD0}" {
   m_LocationRadius 203
   m_MinGroupsLocation 1
  }
 }
}