ARMST_ALIFE_MAIN_CONFIG {
 m_LocationsConf {
  ARMST_ALIFE_LOCATION_CONFIG "{690E617E3A77B1DA}" {
   m_LocationRadius 311
   m_MinGroupsLocation 2
   m_CheckTimerLocation 817
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C66C9F0D7}" {
   m_LocationRadius 358
   m_MinGroupsLocation 2
   m_CheckTimerLocation 877
   m_CheckOrderTimerLocation 925
  }
  ARMST_ALIFE_LOCATION_CONFIG "{69245ACF62C9F73E}" {
   m_LocationRadius 216
   m_MinGroupsLocation 2
   m_CheckTimerLocation 903
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C690578F2}" {
   m_LocationRadius 297
   m_MinGroupsLocation 1
   m_CheckTimerLocation 950
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C771D9434}" {
   m_LocationRadius 257
   m_MinGroupsLocation 1
   m_CheckTimerLocation 787
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C03D43EB5}" {
   m_LocationRadius 264
   m_MinGroupsLocation 1
   m_CheckTimerLocation 835
  }
  ARMST_ALIFE_LOCATION_CONFIG "{690E615C04F6C9EC}" {
   m_LocationRadius 250
   m_MinGroupsLocation 2
   m_CheckTimerLocation 808
  }
  ARMST_ALIFE_LOCATION_CONFIG "{693A786FAE6CBBD0}" {
   m_LocationRadius 142
   m_MinGroupsLocation 1
   m_CheckTimerLocation 773
  }
 }
}