ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2E0A464EB49}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED89C44986}" {
     m_fBuyPrice 3500
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 1
     m_EnableSell 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableSell 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99921E662}" {
     m_EnableBuy 1
     m_EnableSell 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D9835A965F}" {
     m_EnableSell 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2E0A73EC673}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED94CD9BBB}" {
     m_fBuyPrice 10000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EC7BDE8C6C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{698C1C11CAE3AA64}" {
   m_Prefab "{443304F1EC50BC27}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok_Black.et"
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{698C1C11EB8E6AA0}" {
   m_Prefab "{0D39750E5695B9D8}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Gunner.et"
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{698C1C11EDFBA211}" {
   m_Prefab "{4ECD1C3D11E6E810}Prefabs/Backpacks/StalkerBackpack.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EC7BDE8CC0}" {
     m_fBuyPrice 100000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D99921E662}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695A68D9835A965F}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EC57E99E26}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EC57E99E2D}" {
     m_fBuyPrice 15000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2E0D54A7C82}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EC6439039F}" {
     m_fBuyPrice 18000
    }
   }
  }
 }
}