ARMST_DIALOGS_CONFIG {
 m_sNews_Texts {
  "{56478C4C9CFC0697}Configs/GAME_SETTING/DIALOGS/Dialogs_Stalkers.conf"
 }
 m_sDialog_1_Scripts Armst_dialog_news
 m_TraderList {
  ARMST_TRADER_CONFIG "{699C03F145398783}" {
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{699C03F16F673CAC}" {
   m_RequestPrefab {
    "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   }
   m_RewardPrefab {
    "{C918F04D8331C556}Prefabs/Items/change_factions/armst_itm_faction_bandit.et"
   }
  }
 }
}