SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{66D4C9EC38F50E07}" {
   m_Info SCR_UIInfo "{550EDE93E432F64C}" {
    Name "DUTY"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_DUTY
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66D4D423C4B65091}" {
   m_Info SCR_UIInfo "{66D4D423C4B65018}" {
    Name "FREEDOM"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 3
   m_LabelType FACTION_FREEDOM
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66D4D423C5261D76}" {
   m_Info SCR_UIInfo "{66D4D423C5261CD9}" {
    Name "MONOLITH"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 4
   m_LabelType FACTION_MONOLITH
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66D4D423C7B9DD49}" {
   m_Info SCR_UIInfo "{66D4D423C7B9DD36}" {
    Name "BANDITS"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_BANDIT
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66FB0B3B217C50E4}" {
   m_Info SCR_UIInfo "{66FB0B3B217DB322}" {
    Name "SBU"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_SBU
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66FB0B38C05FF3F7}" {
   m_Info SCR_UIInfo "{66FB0B38C05FF357}" {
    Name "ADMIN"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_ADMIN
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{68432D610E6C97ED}" {
   m_Info SCR_UIInfo "{68432D610E6CDA0F}" {
    Name "ADMIN"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_SOJOURN
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{68432D6107A144BB}" {
   m_Info SCR_UIInfo "{68432D6107A14411}" {
    Name "ADMIN"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_ECLIPSE
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{68432D613A7D54E8}" {
   m_Info SCR_UIInfo "{68432D613A7D5440}" {
    Name "ADMIN"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 2
   m_LabelType FACTION_DAWN
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}