SCR_EditorActionList {
 m_Actions {
  SRZ_SendPlayersMessageContextAction "{687CED0795A8D976}" {
   m_Info SCR_UIInfo "{687CED079CC138C6}" {
    Name "Warn for OOC"
    Description "Shows a warning message to players who are going OOC to be IC"
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_bShowOnCooldownNotification 0
   m_message "Reminder: Please stay IC in the Zone. OOC comments are not allowed here. Continued OOC may result in a warning or further action. Thank you."
  }
  SRZ_SendPlayersMessageContextAction "{687CED07D64B702B}" {
   m_Info SCR_UIInfo "{687CED07DEF7CC4C}" {
    Name "Request Walk Away"
    Description "Asks the player to walk away from their group so you can yoink them or talk to them without breaking the immersion of others around them"
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_bShowOnCooldownNotification 0
   m_message "The admin has requested that you step away from the group so they can communicate with you"
  }
 }
}