SCR_EditorActionList {
 m_Actions {
  SCR_ResupplyContextAction "{5678ACB1C80402DF}" {
   m_bEnabled 0
  }
  SCR_BleedCharacterContextAction "{55E8A192FB9EB5F3}" {
   m_bEnabled 0
  }
  SCR_FindInContentBrowserContextAction "{529C95F21D90D1A9}" {
   m_bEnabled 0
  }
  GME_TeleportToSquadmateContextAction "{5DB755396BAD8347}" {
   m_bEnabled 0
  }
  GME_AddGarrisonContextAction "{617456553DC30FA6}" {
   m_bEnabled 0
  }
  SRZ_SendPlayersMessageContextAction "{699F68DEB7CD5B3D}" {
   m_Info SCR_UIInfo "{699F68DD9B68C34B}" {
    Name "Warn for OOC"
    Description "Shows a warning message to players who are going OOC to be IC"
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_message "Reminder: Please stay IC in the Zone. OOC comments are not allowed here. Continued OOC may result in a Strike or further action. Thank you."
  }
  SRZ_SendPlayersMessageContextAction "{699F68DE48C98258}" {
   m_Info SCR_UIInfo "{699F68DE48C8696A}" {
    Name "Request Walk Away"
    Description "Asks the player to step away from the group"
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_message "The admin has requested that you step away from the group so they can communicate with you"
  }
  SRZ_SendPlayersMessageContextAction "{699F68DE45273F53}" {
   m_Info SCR_UIInfo "{699F68DE45273F16}" {
    Name "Warn for Metagaming"
    Description ""
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_message "Warning: You are metagaming. Please only use information your character would know in-game."
  }
  SRZ_SendPlayersMessageContextAction "{699F68DE5F7173BB}" {
   m_Info SCR_UIInfo "{699F68DE5F717386}" {
    Name "Warn for RDM"
    Description ""
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_message "Warning: You have killed another player without valid RP reason. Random Deathmatch is not permitted."
  }
  SRZ_SendPlayersMessageContextAction "{699F68DE519274D7}" {
   m_Info SCR_UIInfo "{699F68DE51927495}" {
    Name "Warn for NLR"
    Description ""
    Icon "{ED4F2ECBD981800D}UI/Textures/Editor/ContextMenu/ContextAction_KickPlayer.edds"
   }
   m_message "Warning: You are breaking New Life Rule. After death you must not return to the same area or remember previous events"
  }
 }
}