SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 "Identity of soldiers" FactionIdentity "{570CFDC6685B6B25}" {
  VisualIdentityArray {
   VisualIdentity "{570CE64C790A3C7D}" {
    Head "{D0B8D7EFB82CEF7B}Prefabs/Characters/Heads/Head_capek.et"
   }
  }
 }
 "Radio encryption key" "thatsforCrimea"
 m_iFactionRadioFrequency 42000
}