SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 "Identity of soldiers" FactionIdentity "{658907E1BCB08455}" {
  VisualIdentityArray {
   VisualIdentity "{570CE64C790A3C7D}" {
    Head "{7E5508ED97DA8699}Prefabs/Characters/Heads/Head_kruglikov.et"
   }
  }
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0E9AFE1E631}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{616A99EA30A8E450}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{616A99EA30A8E453}" {
       m_bEnabled 0
      }
     }
    }
   }
  }
 }
}