SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 "Identity of soldiers" FactionIdentity "{658907E1BCB08455}" {
  VisualIdentityArray {
   VisualIdentity "{570CE64C790A3C7D}" {
    Head "{7E5508ED97DA8699}Prefabs/Characters/Heads/Head_kruglikov.et"
   }
  }
 }
}