SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 "Radio encryption key" "dollaBills"
 m_iFactionRadioFrequency 48000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{69E0E7E05DA61BCE}" : "{2110F8EE27173F6C}Configs/Factions/InventoryItems_EntityCatalog_MERC.conf" {
  }
 }
}