SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66D4D42338EA09A6}" {
   m_sIdentifier "Clothing"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66D5560FABAD7677}" {
     m_sEntityPrefab "{F5D4DBEDE21F5F6D}Prefabs/Items/Equipment/Radios/Radio_DUTY.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66D5560FA2FE93A9}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{684579E6C941C520}" {
     m_sEntityPrefab "{6202BB2A188A6062}Prefabs/Armbands/Prospecting/RedArmband.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{684579E6C941C483}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66D6292DFDEB7B05}" {
     m_sEntityPrefab "{BEF6591A9C8A68DC}Prefabs/Backpacks/Rebreathers.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66D6292DFDEB7AE6}" {
       m_eItemType BACKPACK
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66D6292AA34A6F52}" {
     m_sEntityPrefab "{1C6B51532776CE16}Prefabs/New_Equipment/Vests/ALICE/Vest_belt_SMERSH.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66D6292AA34A6F30}" {
       m_eItemType VEST_AND_WAIST
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66D4F640B3065627}" {
     m_sEntityPrefab "{A82FBAD69AF3E8E8}Prefabs/Hoods/DutyBeret.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66D4F640B30655BB}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66D4D95D1843D7E1}" {
     m_sEntityPrefab "{A961692D355BBEE1}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01_faction.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66D4D95D1843D76F}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68C92C403368F671}" {
     m_sEntityPrefab "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/PaperMap_01_folded_USSR.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C92C41C855DBA8}" {
      }
     }
    }
   }
  }
 }
}