ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{695A68D9F9D52AA8}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68D9FA62C91C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{695A68D9FA35D1E9}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDF47D6E5BCE}" {
   m_Prefab "{E6E4A726377BA2A5}Prefabs/Weapons/Grenades/Grenade_VOG25_Khattabka.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{698CBDF47D6E58B1}" {
     m_fBuyPrice 6000
    }
   }
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{698CBDF47D6E58AA}" {
     m_Category {
      "AMMOS"
     }
     m_TiersSpawn {
      "TIER_2"
      "TIER_3"
     }
     m_iProbability 2
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{698CBDF47D6E58A8}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_WEAPON
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDF47D6E58A9}" {
     m_Actor "MICH_TRADER"
     m_sTraderCategory ARMST_TRADER_WEAPON
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDF47D6E5605}" {
     m_Actor "STORM_TRADER"
     m_sTraderCategory ARMST_TRADER_WEAPON
    }
    ARMST_DATABASE_ITEM_TRADER "{698CBDF47D6E560B}" {
     m_Actor "TUFAN_BARMAN"
     m_sTraderCategory ARMST_TRADER_WEAPON
     m_EnableBuy 0
    }
   }
  }
 }
}