ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF6F4038FAB}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6C9AE03FE}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6CD4C24CA}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6CE923296}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6F1B57AF6}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
 }
}