ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF5CCC50E0A}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69BCAA04231BB207}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_TOOLS
    }
    ARMST_DATABASE_ITEM_TRADER "{69BCAA04237890A4}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_TOOLS
    }
    ARMST_DATABASE_ITEM_TRADER "{69BCAA042367611F}" {
     m_Actor "BANDIT_VENDOR"
     m_sTraderCategory ARMST_TRADER_TOOLS
    }
    ARMST_DATABASE_ITEM_TRADER "{69BCAA042340BB39}" {
     m_Actor "MONOLITH_VENDOR"
     m_sTraderCategory ARMST_TRADER_TOOLS
    }
    ARMST_DATABASE_ITEM_TRADER "{69BCAA0422AFE5DF}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_TOOLS
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6F4038FAB}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6C9AE03FE}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6330D5EA0616B}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_WEAPON
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6330D51961669}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_WEAPON
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6CD4C24CA}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6CE923296}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
    ARMST_DATABASE_ITEM_TRADER "{69BCAA07DF5BFF12}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_WEAPON
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF6F1B57AF6}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
 }
}