ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEDEF5E0361324}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF5E036132D}" {
     m_fBuyPrice 7000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{69367AFA24AF40F6}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69367AFA24AF4170}" {
     m_fBuyPrice 8000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{690913E9774B6DAC}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{690913E9774B6E14}" {
     m_fBuyPrice 12000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF738C06493}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF738C0632D}" {
     m_fBuyPrice 14000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{690913E9760EA874}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{690913E9760EA8C2}" {
     m_fBuyPrice 15000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEDEF736820399}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEDEF73682022B}" {
     m_fBuyPrice 25000
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
   }
  }
 }
}