ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C28E4F1B806}" {
   m_PrefabTrader "{00E41290F2A6E062}Prefabs/New_Equipment/Jackets/sweater/armst_sweater_gray.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EAF2386F}" {
   m_PrefabTrader "{27494A16F172A97B}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EA3EB8E0}" {
   m_PrefabTrader "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EA26A19D}" {
   m_PrefabTrader "{154F2C89FB07FC19}Prefabs/New_Equipment/Helmets/armst_helmet_pasgt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EA5162DB}" {
   m_PrefabTrader "{495754FCBEC85E66}Prefabs/New_Equipment/Armory/armst_armory_6B2.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EA68ADB6}" {
   m_PrefabTrader "{D7B25AAE6F51908A}Prefabs/New_Equipment/Gasmasks/armst_gasmask_gp5.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EB951820}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C28EBBF4118}" {
   m_PrefabTrader "{E394112ABBC198D8}Prefabs/Weapons/Rifles/AKM/Rifle_SOC94.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C376C7FCE58}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
 }
}