ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743384512}" {
   m_PrefabTrader "{94D335E6D55A0AFA}Prefabs/New_Equipment/Jackets/gorka/armst_jacket_gorka_camo_sojourn.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C374338451B}" {
   m_PrefabTrader "{27494A16F172A97B}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743384518}" {
   m_PrefabTrader "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386C44}" {
   m_PrefabTrader "{154F2C89FB07FC19}Prefabs/New_Equipment/Helmets/armst_helmet_pasgt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386CBA}" {
   m_PrefabTrader "{495754FCBEC85E66}Prefabs/New_Equipment/Armory/armst_armory_6B2.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386CB8}" {
   m_PrefabTrader "{D7B25AAE6F51908A}Prefabs/New_Equipment/Gasmasks/armst_gasmask_gp5.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6C}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6D}" {
   m_PrefabTrader "{E394112ABBC198D8}Prefabs/Weapons/Rifles/AKM/Rifle_SOC94.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6A}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
 }
}