ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743384512}" {
   m_PrefabTrader "{5CE06F771B190856}Prefabs/Equipments/Jackets/jacket/armst_jacket_shtormovka_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C374338451B}" {
   m_PrefabTrader "{E1EA4FAEDD70A1C1}Prefabs/Equipments/Pants/jeans/armst_pants_jeans.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743384518}" {
   m_PrefabTrader "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386C44}" {
   m_PrefabTrader "{05283458C159295D}Prefabs/Equipments/Hats/armst_hat_shapka_black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386CBA}" {
   m_PrefabTrader "{495754FCBEC85E66}Prefabs/Equipments/Armory/armst_armory_6B2.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743386CB8}" {
   m_PrefabTrader "{D7B25AAE6F51908A}Prefabs/Equipments/Gasmasks/armst_gasmask_gp5.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6C}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6D}" {
   m_PrefabTrader "{3968B2A856852CBD}Prefabs/Weapons/Handguns/armst_PP91.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3743382A6A}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5823777457}" {
   m_PrefabTrader "{4488C415F3CA1890}Prefabs/Weapons/Magazines/Magazine_9x18_PP91_30rnd_Ball.et"
   m_iCounts 5
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C582351591C}" {
   m_PrefabTrader "{DF7ECE4FEB0F0B69}Prefabs/Equipments/backpack/rukzak_small/bpck_rukzak_base.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5823435EE7}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5821885BCD}" {
   m_PrefabTrader "{26ADE11C416B3840}Prefabs/Weapons/Handguns/Handgun_Knife_base.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5821F0D395}" {
   m_PrefabTrader "{6D1AF5BE65D92CF6}Prefabs/Items/bolts/armst_throw_bolt.et"
   m_iCounts 5
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5821D8503A}" {
   m_PrefabTrader "{33C169417F310F0D}Prefabs/Items/devices/armst_itm_atmos.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BC1E52928}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BC1CC6E8C}" {
   m_PrefabTrader "{83EACE805122087F}Prefabs/Items/Food/armst_itm_food_bread.et"
   m_iCounts 2
  }
 }
}