ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{6926F949A43980C5}" {
   m_sTraderCategoryName2 ARMST_TRADER_MONEY
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{693465B0A3788B00}" {
   m_RewardMoney 8000
  }
  ARMST_MISSIONS_CONFIG "{693465B0A532BA95}" {
   m_RewardMoney 7000
  }
  ARMST_MISSIONS_CONFIG "{693465B0A58B2D96}" {
   m_RewardMoney 6000
  }
  ARMST_MISSIONS_CONFIG "{693465B0A6E0733D}" {
   m_RewardMoney 7000
  }
 }
}