ARMST_DIALOGS_CONFIG {
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{690692C91D74620F}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6913001BC61366B0}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{690692C91B5E2431}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}