ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{6918894EDA434B74}" {
   m_sTraderCategoryName7 ARMST_TRADER_OTHERS
   m_sTraderCategoryName8 ARMST_TRADER_OTHERS
   m_sTraderCategoryName9 ARMST_TRADER_OTHERS
   m_sTraderCategoryName10 ARMST_TRADER_OTHERS
   m_sTraderCategoryName11 ARMST_TRADER_OTHERS
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{691297E69CCCAC18}" {
   m_RewardMoney 8000
  }
  ARMST_MISSIONS_CONFIG "{693465B365BF1E26}" {
   m_RewardMoney 18000
  }
 }
}