ARMST_DIALOGS_CONFIG {
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{693465A66ED570D9}" {
   m_RewardMoney 8000
  }
  ARMST_MISSIONS_CONFIG "{693465AB4531933D}" {
   m_RewardMoney 10000
  }
 }
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{690692C91D74620F}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6913001BC61366B0}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{690692C91B5E2431}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}