ARMST_DIALOGS_CONFIG {
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{693465A8AE82151D}" {
   m_RewardMoney 7000
  }
  ARMST_MISSIONS_CONFIG "{693465A8F1AE1299}" {
   m_RewardMoney 8000
  }
 }
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{690692C92A60EDF4}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6942A16E5183D2E6}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}