ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{6948C106A767643D}" {
   m_sTraderCategoryName2 ARMST_TRADER_MONEY
   m_sTraderCategoryName3 ARMST_TRADER_OTHERS
   m_sTraderCategoryName4 ARMST_TRADER_OTHERS
   m_sTraderCategoryName5 ARMST_TRADER_OTHERS
   m_sTraderCategoryName6 ARMST_TRADER_OTHERS
   m_sTraderCategoryName7 ARMST_TRADER_OTHERS
   m_sTraderCategoryName8 ARMST_TRADER_OTHERS
   m_sTraderCategoryName9 ARMST_TRADER_OTHERS
   m_sTraderCategoryName10 ARMST_TRADER_OTHERS
   m_sTraderCategoryName11 ARMST_TRADER_OTHERS
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{6948C106DCE7F5A9}" {
   m_RewardMoney 8000
  }
  ARMST_MISSIONS_CONFIG "{6948C106DCC025DD}" {
   m_RewardMoney 5000
  }
  ARMST_MISSIONS_CONFIG "{6948C106DCA0C269}" {
   m_RewardMoney 6000
  }
  ARMST_MISSIONS_CONFIG "{6948C106DD475EE2}" {
   m_RewardMoney 6000
  }
 }
}