SR_LootConfig {
 tiers {
  SR_LootTier "{6A1280FC1E51988C}" {
   lootTier "Tier 1"
   categories {
    SR_LootCategory "{6A1280EDBE2BADCA}" {
     category "Drinks"
     items {
      SR_LootItem "{6A1280ED9611A0DE}" {
       prefab "{334A819055D47B97}Prefabs/Items/Food/armst_itm_food_bottle_beer_1.et"
       chance 10
       maxCount 2
      }
      SR_LootItem "{6A1280ED9DBFB7AA}" {
       prefab "{C5C15F24B3C96DE5}Prefabs/Items/Food/armst_itm_food_bottle_beer_2.et"
       chance 10
       maxCount 2
      }
      SR_LootItem "{6A1280ED989A28A7}" {
       prefab "{205D13DDBF2CFA8E}Prefabs/Items/Food/armst_itm_food_bottle_beer_3.et"
       chance 10
       maxCount 2
      }
      SR_LootItem "{6A1280ED8605F02D}" {
       prefab "{1D6936E5CA4073B9}Prefabs/Items/Food/armst_itm_food_bottle_beer_4.et"
       chance 10
       maxCount 2
      }
      SR_LootItem "{6A1280ED85E1ADBE}" {
       prefab "{8290A996301CD643}Prefabs/Items/Food/armst_itm_food_bottle_vodka_1.et"
       chance 10
       maxCount 2
      }
      SR_LootItem "{6A1280ED8EBAD952}" {
       prefab "{91B2B77EC7C215CA}Prefabs/Items/Food/armst_itm_food_bottle_vodka_2.et"
       chance 10
       maxCount 2
      }
     }
    }
    SR_LootCategory "{6A1280EDA05A8ABD}" {
     category "Food"
    }
   }
  }
 }
}