ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2ED11C62CB0}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED11C62C8F}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2ED06FAA2A1}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED06FAA373}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE5A3D00D30}" {
   m_Prefab "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED06FAA373}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{698CBDEC1E62BFE6}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{699544A68EDFB531}" {
     m_Actor "MICH_BARMEN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE5B2C7970D}" {
   m_Prefab "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2ED06FAA373}" {
     m_fBuyPrice 1500
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{698CBDEC14AD1D90}" {
     m_Actor "KB_BARMAN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{699544A682DC44B6}" {
     m_Actor "MICH_BARMEN"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}