ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C00D}" {
   m_PrefabTrader "{7F934FAC7B4676A5}Prefabs/Equipments/Jackets/gorka/armst_jacket_gorka_camo_black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C002}" {
   m_PrefabTrader "{61E01486526D692E}Prefabs/Equipments/Pants/gorka/armst_pants_gorka_tan.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C003}" {
   m_PrefabTrader "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C000}" {
   m_PrefabTrader "{154F2C89FB07FC19}Prefabs/Equipments/Helmets/armst_helmet_pasgt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C001}" {
   m_PrefabTrader "{B2D8B33CF203698E}Prefabs/Equipments/Armory/ASG/armst_armory_asg_browndark.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B814060}" {
   m_PrefabTrader "{977BB82C8AED767C}Prefabs/Equipments/Gasmasks/armst_gasmask_gp7a.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81407F}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81407E}" {
   m_PrefabTrader "{E394112ABBC198D8}Prefabs/Weapons/Rifles/AKM/Rifle_SOC94.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4BBEC086}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BB58881D9}" {
   m_PrefabTrader "{07805AE177F52646}Prefabs/Weapons/Magazines/7x62/Magazine_762x39_AKM_10rnd_Ball.et"
   m_iCounts 6
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BB5F491D9}" {
   m_PrefabTrader "{F48174E15A316FFF}Prefabs/Equipments/backpack/rukzak_small/armst_bpck_rukzak_tan.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BB5DFB58B}" {
   m_PrefabTrader "{83EACE805122087F}Prefabs/Items/Food/armst_itm_food_bread.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5BB5C7B858}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B7A2E1D1C}" {
   m_PrefabTrader "{33C169417F310F0D}Prefabs/Items/devices/armst_itm_atmos.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B7A09696D}" {
   m_PrefabTrader "{6D1AF5BE65D92CF6}Prefabs/Items/bolts/armst_throw_bolt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B7A672EF8}" {
   m_PrefabTrader "{26ADE11C416B3840}Prefabs/Weapons/Handguns/Handgun_Knife_base.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B75483337}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B74B1FFD8}" {
   m_PrefabTrader "{CB67A30D05AA4F29}Prefabs/Items/Medicine/armst_itm_medkit_ai2.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{6A4D0C5B15C00B01}" {
   m_PrefabTrader "{65EF51BF87A5CCA3}Prefabs/Items/devices/armst_itm_olimp.et"
  }
 }
}