ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E7929E}" {
   m_PrefabTrader "{94D335E6D55A0AFA}Prefabs/New_Equipment/Jackets/gorka/armst_jacket_gorka_camo_sojourn.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E79286}" {
   m_PrefabTrader "{821386465B3C63AB}Prefabs/Characters/Uniforms/Pants_Tracksuit/Pants_Tracksuit_Navy.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E79285}" {
   m_PrefabTrader "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E79284}" {
   m_PrefabTrader "{154F2C89FB07FC19}Prefabs/New_Equipment/Helmets/armst_helmet_pasgt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E77937}" {
   m_PrefabTrader "{AE4136E8C5FBAD7B}Prefabs/New_Equipment/Armory/armst_armory_dbsh5.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E77930}" {
   m_PrefabTrader "{FB2F8CCC3629F952}Prefabs/New_Equipment/Gasmasks/armst_gasmask_gp7b.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E77931}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E77932}" {
   m_PrefabTrader "{5BFF97EFD0BF6D9F}Prefabs/Weapons/Rifles/AKM/Rifle_AKM.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F12E77933}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
 }
}