ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C00D}" {
   m_PrefabTrader "{BCBB108781BC361E}Prefabs/New_Equipment/Jackets/sweater/armst_sweater_green.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C002}" {
   m_PrefabTrader "{AC7F9BCA3DA1002D}Prefabs/Characters/Uniforms/Pants_Tracksuit/Pants_Tracksuit_Black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C003}" {
   m_PrefabTrader "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C000}" {
   m_PrefabTrader "{154F2C89FB07FC19}Prefabs/New_Equipment/Helmets/armst_helmet_pasgt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81C001}" {
   m_PrefabTrader "{AE4136E8C5FBAD7B}Prefabs/New_Equipment/Armory/armst_armory_dbsh5.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B814060}" {
   m_PrefabTrader "{977BB82C8AED767C}Prefabs/New_Equipment/Gasmasks/armst_gasmask_gp7a.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81407F}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4B81407E}" {
   m_PrefabTrader "{96DFD2E7E63B3386}Prefabs/Weapons/Rifles/AK74/armst_AK74N.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69A54C3F4BBEC086}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
 }
}