SR_LootConfig {
 tiers {
  SR_LootTier "{6A1105AB5496BE70}" {
   categories {
    SR_LootCategory "{6A1105AB55AC6106}" {
     items {
      SR_LootItem "{6A1105AB52E3A574}" {
      }
     }
    }
   }
  }
 }
}