SR_MasterRankLootConfig {
 m_aRankList {
  SR_RankLootEntry "{69A54C2855547E1A}" {
   m_aLootConfigs {
    "{EE697D7413777D3A}Configs/GAME_SETTING/STARTING/stalker_starting.conf"
   }
  }
  SR_RankLootEntry "{69A54C3F0CD92A74}" {
   m_eRank EXPERIENCED
   m_aLootConfigs {
    "{817FF39608F08645}Configs/Stalker_Ranks/LootConfigs/EXPERIENCED/EXPERIENCED1.conf"
    "{20D9BC8DB56D6CE2}Configs/Stalker_Ranks/LootConfigs/EXPERIENCED/EXPERIENCED2.conf"
   }
  }
 }
}