ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2EA838EC7DA}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230876849DA}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6023086B0A171}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6023086EB99B4}" {
     m_Actor "BANDIT_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230864397FE}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B6023084885A44}" {
     m_Actor "MONOLITH_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EA8F0DAFE8}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230A7D13A57}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230A727967D}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230A76C8DF4}" {
     m_Actor "BANDIT_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230A74FC5B4}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B60230A6AFB30A}" {
     m_Actor "MONOLITH_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB3A4FC07}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB77AC20C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB93764FC}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602306C92FBCB}" {
     m_Actor "DUTY_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602306CF48DF6}" {
     m_Actor "BANDIT_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602306CDE3B8C}" {
     m_Actor "FREEDOM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602306C3AB5B2}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
    ARMST_DATABASE_ITEM_TRADER "{69B602306C205A58}" {
     m_Actor "MONOLITH_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}