ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2EA838EC7DA}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EA8F0DAFE8}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB3A4FC07}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB77AC20C}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2EAB93764FC}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68D99442CDC8}" {
     m_Actor "MICH_BARMEN"
     m_EnableBuy 1
    }
   }
  }
 }
}