SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{699B5A3B8B12D644}" {
   m_Info SCR_UIInfo "{699B5A3B8B12D6EA}" {
    Name "DUTY"
    Icon "{7190C4317BE8EF18}Assets/Textures/Icons/dutyicon.edds"
   }
   m_Order 12
   m_LabelType FACTION_DUTY
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSettingExtended "{699B5A3B82FBC5DB}" {
   m_Info SCR_UIInfo "{699B5A3B82FBC593}" {
    Name "FREEDOM"
    Icon "{378167D975513956}Assets/Textures/Icons/freedomicon.edds"
   }
   m_Order 13
   m_LabelType FACTION_FREEDOM
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSettingExtended "{699B5A3BB95AFE05}" {
   m_Info SCR_UIInfo "{699B5A3BB95AFEAE}" {
    Name "BANDITS"
    Icon "{96D3A545173A1ED8}Assets/Textures/Icons/banditicon.edds"
   }
   m_Order 14
   m_LabelType BANDITS
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSettingExtended "{699B5A3B505F17DD}" {
   m_Info SCR_UIInfo "{699B5A3B505F178B}" {
    Name "UKM"
    Icon "{D4CAB9CB63E132DE}Prefabs/Factions/Groups/ARMYS.edds"
   }
   m_Order 15
   m_LabelType FACTION_SBU
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSettingExtended "{699B5A3B0E5FE8F3}" {
   m_Info SCR_UIInfo "{699B5A3B0E5FE893}" {
    Name "MONOLITH"
    Icon "{77D1D73C132038FB}Assets/Textures/Icons/monoicon.edds"
   }
   m_Order 12
   m_LabelType FACTION_MONOLITH
   m_LabelGroupType FACTION
  }
 }
}