ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{69B282A476415FAB}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B282A476415FAA}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B282A465D45995}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B282A465D45A39}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B282A59E682121}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B282A59E682191}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849A862942E2}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849A86294C9E}" {
     m_fBuyPrice 3000
    }
   }
  }
  ARMST_DATABASE_ITEM "{6A6C042638164E92}" {
   m_Prefab "{A9366A2F0659A50E}Prefabs/Equipments/Jackets/gorka/armst_jacket_gorka_camo_UKM.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{6A6C042638164ED2}" {
     m_fBuyPrice 4000
     m_RequiredFaction FACTION_ARMY
     m_fProtectionToxicLevel 10
     m_fProtectionRadiactiveLevel 5
     m_fProtectionPhysicalsLevel 12
     m_fProtectionThermoLevel 15
     m_fProtectionElectroLevel 5
     m_fReliableModifierLevel 15
     m_PrefabRepairs "{7CEF426ABDE2DCA1}Prefabs/Items/repairs/armst_itm_repair_clothes.et"
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{6A6C042631360218}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
    }
   }
  }
 }
}