ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82FB}" {
   m_PrefabTrader "{AD1B343E015F2D11}Prefabs/Weapons/Rifles/M3A1/BC_M3A1.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82F6}" {
   m_PrefabTrader "{0B17FB1F4A9F5289}Prefabs/Weapons/Magazines/M3A1/BC_Magazine_45acp_M3A1_30rnd_Ball.et"
   m_iCounts 4
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82F1}" {
   m_PrefabTrader "{B274446074F15684}Prefabs/Armbands/BanditArmband.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{666402A0AA7F0200}" {
   m_PrefabTrader "{8290A996301CD643}Prefabs/Items/Food/armst_itm_food_bottle_vodka_1.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{692125E8CA64E58F}" {
   m_PrefabTrader "{AC04D0D1EABC994F}Prefabs/Items/devices/Radio_R148.et"
  }
 }
}