ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82FB}" {
   m_PrefabTrader "{AD1B343E015F2D11}Prefabs/Weapons/Rifles/M3A1/BC_M3A1.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82F6}" {
   m_PrefabTrader "{0B17FB1F4A9F5289}Prefabs/Weapons/Magazines/M3A1/BC_Magazine_45acp_M3A1_30rnd_Ball.et"
   m_iCounts 4
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C4257AD82F1}" {
   m_PrefabTrader "{B274446074F15684}Prefabs/Armbands/BanditArmband.et"
   m_iCounts 1
  }
  ARMST_PLAYER_START_CONF_DATA "{666402A0AA7F0200}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{692125E8CA64E58F}" {
   m_PrefabTrader "{83EACE805122087F}Prefabs/Items/Food/armst_itm_food_bread.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69B7479539EB2672}" {
   m_PrefabTrader "{1E3FDB052BD59DFD}Prefabs/Characters/Vests/Vest_6B2/Vest_6B2_Black.et"
  }
 }
}