ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{666402989636098B}" {
   m_PrefabTrader "{4575737B3D3A4505}Prefabs/Weapons/Magazines/5x56/Magazine_556x45_STANAG_30rnd_M196_Tracer.et"
   m_iCounts 5
  }
  ARMST_PLAYER_START_CONF_DATA "{6664029887739ED1}" {
   m_PrefabTrader "{3E413771E1834D2F}Prefabs/Weapons/Rifles/Rifle_M16A2.et"
   m_iCounts 1
  }
  ARMST_PLAYER_START_CONF_DATA "{666402A420E14BDF}" {
   m_PrefabTrader "{4F71E7468E78DDD2}Prefabs/Characters/Handwear/Gloves_Leather_01/Gloves_Leather_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{666402A7DE9BEB4C}" {
   m_PrefabTrader "{1FA63851C30789B9}Prefabs/New_Equipment/Gasmasks/armst_gasmask_resp_factions.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{692125E8991F9B1C}" {
   m_PrefabTrader "{AC04D0D1EABC994F}Prefabs/Items/devices/Radio_R148.et"
  }
 }
}