ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E5A8}" {
   m_PrefabTrader "{81631BDFDFCF81C6}Prefabs/MERCGEAR/MERC JACKET/MERC GORKA.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E596}" {
   m_PrefabTrader "{DEDB16D42BE68D48}Prefabs/MERCGEAR/MERCPANTS/armst_pants_crye_MERC.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E592}" {
   m_PrefabTrader "{1D1CF01775CD47F4}Prefabs/Backpacks/Buttpack.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E59C}" {
   m_PrefabTrader "{F237881A800ACFB9}Prefabs/New_Equipment/Gasmasks/armst_gasmask_mv35.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E59A}" {
   m_PrefabTrader "{028FA91037FEA275}Prefabs/MERCGEAR/MERCVEST/MERCBEST.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E585}" {
   m_PrefabTrader "{6993C08FA6BAA2FE}Prefabs/Weapons/Rifles/AR15/Rifle_Pronto_AR15_Base.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E587}" {
   m_PrefabTrader "{D8F2CA92583B23D3}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M855_M856_Last_5Tracer.et"
   m_iCounts 7
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C41CFD9E582}" {
   m_PrefabTrader "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E08DE35C1B}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E08DC8A452}" {
   m_PrefabTrader "{CB67A30D05AA4F29}Prefabs/Items/Medicine/armst_itm_medkit_ai2.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E097F96C09}" {
   m_PrefabTrader "{E787ABC7B9D4A084}Prefabs/Items/Medicine/armst_itm_stim_derad.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E0AB953CAC}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E0A12D6841}" {
   m_PrefabTrader "{83EACE805122087F}Prefabs/Items/Food/armst_itm_food_bread.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E0A436FFF3}" {
   m_PrefabTrader "{445F57EDB909E6B8}Prefabs/Items/Others/dogtags/armst_dogtag_merc.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E0495617B2}" {
   m_PrefabTrader "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E052C5FE3C}" {
   m_PrefabTrader "{D62181862478033C}Prefabs/Characters/Handwear/Gloves_Leather_01/STALKER_eXplorer_CombatGloves_black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E026CBC692}" {
   m_PrefabTrader "{3D400368B9CB8866}Prefabs/MERCGEAR/PSGT/MERCPASGT.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E1CC219227}" {
   m_PrefabTrader "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/armst_M9.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69DD43E1DB847261}" {
   m_PrefabTrader "{DFFBF5F097FCF797}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Base.et"
   m_iCounts 3
  }
 }
}