ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{660AD1A276F0E0D9}" {
   m_PrefabTrader "{5CE06F771B190856}Prefabs/New_Equipment/Jackets/jacket/armst_jacket_shtormovka_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{660AD1A27B319ED8}" {
   m_PrefabTrader "{529701B313900B02}Prefabs/Equipments/Gasmasks/armst_gasmask_resp.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{698B7BF020E0ABA2}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{698B7BF021C69300}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{698B7BFFCA45199B}" {
   m_PrefabTrader "{B8CBA02D61B3B70E}Prefabs/Items/Food/armst_itm_food_crackers.et"
  }
 }
}