ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{660AD1A276F0E0D9}" {
   m_PrefabTrader "{5CE06F771B190856}Prefabs/Equipments/Jackets/jacket/armst_jacket_shtormovka_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{660AD1A274C2622F}" {
   m_PrefabTrader "{109BEF8183F683BB}Prefabs/Equipments/Pants/armst_pants_stalker.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{660AD1A27B319ED8}" {
   m_PrefabTrader "{1FA63851C30789B9}Prefabs/New_Equipment/Gasmasks/armst_gasmask_resp_factions.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{660AD1AF940FD88E}" {
   m_iCounts 6
  }
  ARMST_PLAYER_START_CONF_DATA "{6995709893D6099B}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{699570989C16BC05}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{699570989D70101F}" {
   m_PrefabTrader "{B8CBA02D61B3B70E}Prefabs/Items/Food/armst_itm_food_crackers.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69969C066DB5A22D}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69969C066385C2ED}" {
   m_PrefabTrader "{BD5C4266D195A8E2}Prefabs/Equipments/Armory/armst_vest_hunt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69970DB52AD92279}" {
   m_PrefabTrader "{323641C91965842E}Prefabs/Characters/HeadGear/Hat_Ushanka_01/Hat_Ushanka_01_unfolded.et"
  }
 }
}