ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90DB1F4}" {
   m_PrefabTrader "{FDDEFE239A6DE08B}Prefabs/Equipments/Jackets/bomber/armst_bomber_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90DB1E5}" {
   m_PrefabTrader "{E1EA4FAEDD70A1C1}Prefabs/Equipments/Pants/jeans/armst_pants_jeans.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90DB1DA}" {
   m_PrefabTrader "{1FA63851C30789B9}Prefabs/New_Equipment/Gasmasks/armst_gasmask_resp_factions.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90DB1D9}" {
   m_PrefabTrader "{FA1A1C2700C3306D}Prefabs/Equipments/backpack/armst_bpck_kolobok.et"
   m_iCounts 6
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D7E57}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D7E52}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D7E53}" {
   m_PrefabTrader "{B8CBA02D61B3B70E}Prefabs/Items/Food/armst_itm_food_crackers.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D117A}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D1175}" {
   m_PrefabTrader "{BD5C4266D195A8E2}Prefabs/Equipments/Armory/armst_vest_hunt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0D90D1174}" {
   m_PrefabTrader "{622D7C093434AAF3}Prefabs/Equipments/Hats/armst_hat_shapka_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0B8362E7E}" {
   m_PrefabTrader "{0D469F42B65E350E}Prefabs/Weapons/Handguns/armst_TT.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0B81121EA}" {
   m_PrefabTrader "{AA99F5E678010DB3}Prefabs/Weapons/Magazines/Magazine_763x25_TT_8rnd_Ball.et"
   m_iCounts 5
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA017BB0D87}" {
   m_PrefabTrader "{5DF442DF18F312F3}Prefabs/Equipments/Boots/armst_boots_soviet.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA017A1F0C3}" {
   m_PrefabTrader "{33C169417F310F0D}Prefabs/Items/devices/armst_itm_atmos.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA017F7DCB0}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA035CFBA9C}" {
   m_PrefabTrader "{C81B78522044EA72}Prefabs/Items/light/HeadLamp.et"
  }
 }
}