ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595F1}" {
   m_PrefabTrader "{BD223DD4B760D81E}Prefabs/Equipments/Jackets/sweater/armst_sweater_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595EE}" {
   m_PrefabTrader "{27494A16F172A97B}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595E9}" {
   m_PrefabTrader "{1FA63851C30789B9}Prefabs/New_Equipment/Gasmasks/armst_gasmask_resp_factions.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595E8}" {
   m_PrefabTrader "{FA1A1C2700C3306D}Prefabs/Equipments/backpack/armst_bpck_kolobok.et"
   m_iCounts 6
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595EB}" {
   m_PrefabTrader "{08FA980C3B2932F6}Prefabs/Items/Medicine/armst_itm_bandage.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA0524595EA}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
   m_iCounts 2
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA052461FE8}" {
   m_PrefabTrader "{B8CBA02D61B3B70E}Prefabs/Items/Food/armst_itm_food_crackers.et"
   m_iCounts 3
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA052461FE6}" {
   m_PrefabTrader "{FDC565C57D29232F}Prefabs/Armbands/LonerPatch.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA052461FE5}" {
   m_PrefabTrader "{BD5C4266D195A8E2}Prefabs/Equipments/Armory/armst_vest_hunt.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA052461FE4}" {
   m_PrefabTrader "{622D7C093434AAF3}Prefabs/Equipments/Hats/armst_hat_shapka_brown.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA052461FE3}" {
   m_PrefabTrader "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/armst_M9.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA05246E222}" {
   m_PrefabTrader "{DFFBF5F097FCF797}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Base.et"
   m_iCounts 5
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA1C50A1EC2}" {
   m_PrefabTrader "{F48174E15A316FFF}Prefabs/Equipments/backpack/rukzak_small/armst_bpck_rukzak_tan.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA1C5738EF2}" {
   m_PrefabTrader "{6E2790C4C516701B}Prefabs/Items/devices/armst_itm_pda.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA1C5599E39}" {
   m_PrefabTrader "{33C169417F310F0D}Prefabs/Items/devices/armst_itm_atmos.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA1C54137A0}" {
   m_PrefabTrader "{5DF442DF18F312F3}Prefabs/Equipments/Boots/armst_boots_soviet.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{69976DA1C4AE77A7}" {
   m_PrefabTrader "{C81B78522044EA72}Prefabs/Items/light/HeadLamp.et"
  }
 }
}