ARMST_PLAYER_START_CONF_Config {
 m_WikiData {
  ARMST_PLAYER_START_CONF_DATA "{663E9C4217E88FAB}" {
   m_PrefabTrader "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{663E9C40C047142D}" {
   m_PrefabTrader "{443304F1EC50BC27}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok_Black.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{692125E8EA33A65C}" {
   m_PrefabTrader "{AC04D0D1EABC994F}Prefabs/Items/devices/Radio_R148.et"
  }
  ARMST_PLAYER_START_CONF_DATA "{666402A69ED541F0}" {
   m_PrefabTrader "{52D3FE1E430900D3}Prefabs/Items/Food/armst_itm_food_canteen_water.et"
  }
 }
}