ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{69B2849A09731651}" {
   m_Prefab "{1915830794F1D2BA}Prefabs/Equipments/Suits/ZIS/armst_zis_brown.et"
   m_ChildrensPrefabs {
    "{594948B320B7412E}Prefabs/Equipments/Suits/ZIS/armst_zis_gray.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849A09731650}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 60
     RepairCount 50
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849A0973164C}" {
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A09731649}" {
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A0973164B}" {
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A09731645}" {
     m_fReputationReq 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69E9458FEF92D8A1}" {
     m_sTraderCategory ARMST_TRADER_CLOTHES
     m_EnableBuy 0
     m_fFixedPrice 40000
     m_fReputationReq 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849B51809DD9}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849B51809D40}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 60
     RepairCount 50
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849B51809D4B}" {
     m_fReputationReq 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849B5BAB4CE4}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849B5BAB4C19}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 60
     RepairCount 50
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849B41FE5AEE}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849B41FE5A16}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 60
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849B41FE5A1E}" {
     m_fReputationReq 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849B438340C8}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849B43834054}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 60
     RepairCount 50
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849B43834058}" {
     m_fReputationReq 0
    }
   }
  }
  ARMST_DATABASE_ITEM "{69B2849B479A0D28}" {
   m_ChildrensPrefabs {
    "{188CAE54A22D3CBA}Prefabs/Equipments/Suits/ZIS/armst_zis_green.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69B2849B479A0CBA}" {
     m_fBuyPrice 60000
     m_fProtectionRadiactiveLevel 61
     RepairCount 50
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849B479A0CA5}" {
     m_fReputationReq 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69E9458F9F8603C9}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
     m_fFixedPrice 30000
    }
   }
  }
  ARMST_DATABASE_ITEM "{69EB3EE331461ED8}" {
   m_Prefab "{AEA517734C6F47AE}Prefabs/Equipments/Suits/ZIS/armst_zis_blue.et"
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{69EB3EE331461DB2}" {
     m_fBuyPrice 60000
     m_RequiredFaction FACTION_KB
     m_fProtectionToxicLevel 30
     m_fProtectionRadiactiveLevel 61
     m_fProtectionPhysicalsLevel 35
     m_fProtectionThermoLevel 40
     m_fProtectionElectroLevel 45
     m_fReliableModifierLevel 50
     m_PrefabRepairs "{7CEF426ABDE2DCA1}Prefabs/Items/repairs/armst_itm_repair_clothes.et"
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69EB3EE331461DAD}" {
     m_Actor "MERC_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
     m_fTraderCount 0
     m_fFixedPrice 30000
    }
    ARMST_DATABASE_ITEM_TRADER "{69EB3EE32BCD0E64}" {
     m_EnableBuy 0
    }
   }
  }
 }
}