ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{69B2849A09731651}" {
   m_ChildrensPrefabs {
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69B2849A0973164C}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A09731649}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A0973164B}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69B2849A09731645}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{69E8DDE82D9887EE}" {
     m_Actor "MERC_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
     m_fFixedPrice 40000
     m_fReputationReq 0
    }
   }
  }
 }
}