ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{68EEB2FC816122DC}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EE97D79AD8150E}" {
     m_fProtectionRadiactiveLevel 28
     m_fProtectionPhysicalsLevel 35
     m_fProtectionThermoLevel 25
    }
   }
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{695A68DA672DCF27}" {
     m_EnableBuy 0
    }
    ARMST_DATABASE_ITEM_TRADER "{695AD5E6039EEA5C}" {
     m_EnableBuy 1
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5EA035EC922}" {
   m_ChildrensPrefabs +{
    "{F434801B55CAE6A7}Prefabs/New_Equipment/Suits/rhuno/armst_rhuno_suit_duty.et"
    "{4D7E71276F508807}Prefabs/New_Equipment/Suits/rhuno/armst_rhuno_suit_freedom.et"
    "{A904623FB4AD4903}Prefabs/New_Equipment/Suits/rhuno/armst_rhuno_suit_mono.et"
    ""
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5EA035EC941}" {
     m_fProtectionRadiactiveLevel 26
     m_fProtectionPhysicalsLevel 37
     m_fProtectionThermoLevel 24
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC9B3AFF01}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EEAAA4EBDA}" {
     m_fProtectionToxicLevel 16
     m_fProtectionRadiactiveLevel 35
     m_fProtectionThermoLevel 21
     m_fProtectionElectroLevel 22
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5EA329BCF4F}" {
   m_ChildrensPrefabs {
    "{C16058D1EFB14B35}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_army.et"
    "{5C9942F182F9A92E}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_duty.et"
    "{6CA5D5B7211DA10D}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_freedom.et"
    "{FC62653D3FD746E2}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_mono.et"
    ""
    "{8C83A0B54398665B}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_kb.et"
    "{82192DE8626D18F5}Prefabs/Equipments/Suits/kirza/armst_suit_kirza_merc.et"
    "{9FE89B4CBEC23891}Prefabs/New_Equipment/Suits/kirza/armst_suit_kirza_storm.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5EA329BCFED}" {
     m_fProtectionToxicLevel 25
     m_fProtectionRadiactiveLevel 30
     m_fProtectionPhysicalsLevel 29
     m_fProtectionThermoLevel 27
     m_fProtectionElectroLevel 28
    }
   }
  }
  ARMST_DATABASE_ITEM "{698CBDE248FA2418}" {
   m_Prefab "{619B7F1D529FA4F9}Prefabs/New_Equipment/Suits/srev/armst_suit_srev_duty.et"
   m_ChildrensPrefabs {
    "{D15C9FD4F6383A56}Prefabs/New_Equipment/Suits/srev/armst_suit_srev_freedom.et"
    "{4A9FEB3164ECAB33}Prefabs/New_Equipment/Suits/srev/armst_suit_srev_monolith.et"
   }
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{695AD5EA329BCFED}" {
     m_fProtectionToxicLevel 25
     m_fProtectionRadiactiveLevel 30
     m_fProtectionPhysicalsLevel 29
     m_fProtectionThermoLevel 27
     m_fProtectionElectroLevel 28
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FC88480D77}" {
   m_ItemStats {
    ARMST_DATABASE_ITEM_STATS "{68EEB2EE1E81E275}" {
     m_fBuyPrice 25000
    }
   }
  }
  ARMST_DATABASE_ITEM "{68EEB2FCBA6BD40B}" {
   m_ItemLoot {
    ARMST_DATABASE_ITEM_LOOT "{695A68C79B91B834}" {
     m_TiersSpawn {
      "TIER_3"
     }
    }
   }
  }
  ARMST_DATABASE_ITEM "{695AD5EA26E42D79}" {
   m_ChildrensPrefabs +{
    "{C0E212F31FB73A18}Prefabs/New_Equipment/Suits/SpecA/armst_suit_specA_duty.et"
    "{9A585BE126FA6342}Prefabs/New_Equipment/Suits/SpecA/armst_suit_specA_freedom.et"
    "{9DD2F0D7FED095BC}Prefabs/New_Equipment/Suits/SpecA/armst_suit_specA_mono.et"
    "{F8E7124CB5D8EA12}Prefabs/New_Equipment/Suits/SpecA/armst_suit_specA_ukm.et"
   }
  }
 }
}