ARMST_DATABASE_ITEMS {
 m_ItemsList {
  ARMST_DATABASE_ITEM "{69B2849A3AA1433A}" {
   m_ItemTrader {
    ARMST_DATABASE_ITEM_TRADER "{69E9458F09116BBF}" {
     m_Actor "UKM_VENDOR"
     m_sTraderCategory ARMST_TRADER_CLOTHES
     m_fFixedPrice 10000
     m_fReputationReq 90
    }
   }
  }
 }
}