SCR_MissionHeader {
 World "{712F4DB57F44C01C}MAINSRMAP.ent"
 m_sName "The Zone "
 m_sAuthor "TheGuy+SRTeam"
 m_sDescription "A world for use by SR team"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_fDayTimeAcceleration 3
 m_fNightTimeAcceleration 6
 m_eGME_GlobalAISkill REGULAR
}