SCR_MissionHeader {
 World "{712F4DB57F44C01C}MAINSRMAP.ent"
 m_sName "StalkerReforged "
 m_sAuthor "TheGuy+SRTeam"
 m_sDescription "Step into the Zone and experience its wonders and horrors. Anomalies, mutants, and danger lurk around every corner. Will you survive, or die trying?"
 m_sDetails "Step into the Zone and experience its wonders and horrors. Anomalies, mutants, and danger lurk around every corner. Will you survive, or die trying?"
 m_sIcon "{098CFE8C6B42E82C}SRlogoupdated.edds"
 m_sLoadingScreen "{3CD9248F9B1889CA}Use AI Image Jun 10, 2026, 17_22_15.edds"
 m_sPreviewImage "{098CFE8C6B42E82C}SRlogoupdated.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_fDayTimeAcceleration 4
 m_fNightTimeAcceleration 7.5
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_iMapMarkerLimitPerPlayer 0
 m_eGME_GlobalAISkill VETERAN
}