ARMST_DIALOGS_CONFIG {
 m_TraderList {
  ARMST_TRADER_CONFIG "{692A819A577408CB}" {
   m_sTraderCategoryName2 ARMST_TRADER_MONEY
   m_sTraderCategoryName3 ARMST_TRADER_OTHERS
   m_sTraderCategoryName4 ARMST_TRADER_OTHERS
   m_sTraderCategoryName5 ARMST_TRADER_OTHERS
   m_sTraderCategoryName6 ARMST_TRADER_OTHERS
   m_sTraderCategoryName7 ARMST_TRADER_OTHERS
   m_sTraderCategoryName8 ARMST_TRADER_OTHERS
   m_sTraderCategoryName9 ARMST_TRADER_OTHERS
   m_sTraderCategoryName10 ARMST_TRADER_OTHERS
   m_sTraderCategoryName11 ARMST_TRADER_OTHERS
  }
 }
 m_MissionsList {
  ARMST_MISSIONS_CONFIG "{691134C4B666A1E9}" {
   m_RewardMoney 7000
  }
  ARMST_MISSIONS_CONFIG "{691134C436A736DC}" {
   m_RewardMoney 6000
  }
  ARMST_MISSIONS_CONFIG "{693465B087CDE2BA}" {
   m_RewardMoney 6000
  }
  ARMST_MISSIONS_CONFIG "{691134C4032710F0}" {
   m_RewardMoney 4000
  }
 }
}