ARMST_DIALOGS_CONFIG {
 m_TravelList {
  ARMST_FAST_TRAVEL_CONFIG "{6904D31CC82049D5}" {
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6904D31CCC5BFEE9}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6913001BF52C243A}" {
   m_fMinimalReputation -100
  }
  ARMST_FAST_TRAVEL_CONFIG "{6942A16E58807170}" {
   m_FactionTrader FACTION_ALL
   m_fMinimalReputation -100
  }
 }
}