WeatherStateMachine {
 States {
  SCR_WeatherState "{6608F00AA10D86F9}" {
   StateDurationHoursMin 0.167
   StateDurationHoursMax 1.3
  }
  SCR_WeatherState "{6908B09A9C8E76E5}" {
   StateDurationHoursMin 4.4
   StateDurationHoursMax 8.7
  }
 }
 StartState "Cloudy"
}