SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{698D05E820F71479}" {
   m_sIdentifier "EVERYTHING"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{698D05E830151477}" {
     m_sEntityPrefab "{221AED80163B7C60}Prefabs/Weapons/Rifles/Shotgun/armst_spas12.et"
    }
   }
  }
 }
}