SCR_EditorAttributeList {
 m_aAttributes {
  ARMST_MoneyChangeEditorAttribute "{690F0CA9B6756332}" {
   m_baseValues SCR_EditorAttributeBaseValues "{69105AEE6B07A980}" {
    m_fMax 5000000
   }
  }
  ARMST_FactionChangeEditorAttribute "{692677CE44FB7000}" {
   m_baseValues SCR_EditorAttributeBaseValues "{692677CE44FB7002}" {
   }
  }
  SR_PlayerRankAttribute "{69A516180FD2DFEC}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{69A16EFDA75FEF2C}" {
    Name "Stalker Rank"
    Description "Change the stalker rank of a player"
   }
   m_CategoryConfig "{8A757725BEAC5B36}Configs/Editor/AttributeCategories/Character.conf"
   m_Layout "{2ECAE6EA5F6855C9}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Dropdown.layout"
   m_aValues {
    SCR_EditorAttributeFloatStringValueHolder "{69A32A50B64C354C}" {
     m_sEntryName "ROOKIE"
    }
    SCR_EditorAttributeFloatStringValueHolder "{69A32A50BD672174}" {
     m_sEntryName "EXPERIENCED"
     m_fEntryFloatValue 1
    }
    SCR_EditorAttributeFloatStringValueHolder "{69A32A5094815008}" {
     m_sEntryName "VETERAN"
     m_fEntryFloatValue 2
    }
    SCR_EditorAttributeFloatStringValueHolder "{69A32A5094A86F6A}" {
     m_sEntryName "EXPERT"
     m_fEntryFloatValue 3
    }
    SCR_EditorAttributeFloatStringValueHolder "{69A32A5094C1B2B5}" {
     m_sEntryName "MASTER"
     m_fEntryFloatValue 4
    }
   }
  }
 }
}