SCR_EditorAttributeList {
 m_aAttributes {
  ARMST_FactionChangeEditorAttribute "{692677CE44FB7000}" {
   m_baseValues SCR_EditorAttributeBaseValues "{692677CE44FB7002}" {
   }
  }
  GME_FactionsCharacterEditorAttribute "{699F42C835B388D6}" {
   m_aValues {
    SCR_EditorAttributeFloatStringValueHolder "{699F42D79539B047}" {
     m_sEntryName "FACTION_DUTY"
     m_fEntryFloatValue 1
    }
   }
  }
 }
}